### ISSUE TITLE
商品显示【抢购】无法加入购物车

### ISSUE THREAD

**Issue by 646420882** [tychxn/jd-assistant#10]
![11111](https://user-images.githubusercontent.com/22008693/47269669-d2e60980-d593-11e8-9373-897b69d73913.png)

不知道这种是不是预约，无法加入购物车，这种准点抢购的要怎么抢呢

**Comment by tychxn** [comment]
看着应该是直接抢购的，跟普通商品的下单流程不太一样（ps:京东的下单方式真的是太多了）
如果可以的话，麻烦抓一下抢购流程的数据包发给我，我看一下怎么处理～谢谢🙏

**Comment by 646420882** [comment]
不好意思，没能抓到包，抢购的时候跳转了。

**Comment by 646420882** [comment]
原来这种是不能加入购物车的，点了抢购之后会自动跳转到下单页面，好像界面跟普通的下单又有点不一样

**Comment by tychxn** [comment]
一般这种抢购都是直接达到订单页面，然后选择提交。

- 如果使用浏览器`开发者工具`抓包，记得勾选`Preserve log`，即使跳转了页面，数据包依旧保留。
- 如果使用Fiddler这类工具，直接抓就可以了。

10月25日上午我关注一下看看……

**Comment by 646420882** [comment]
好的，手机已经抢到了。。。我用的是chrome的开发者工具，开启了持续日志，但是新标签打开就没办法抓了

**Comment by tychxn** [comment]
已抓包完并完成该功能的代码。
