### ISSUE TITLE
risk_control 这个参数每次刷新页面后都会改变

### ISSUE THREAD

**Issue by jy024929** [tychxn/jd-assistant#101]
risk_control 这个参数每次刷新页面都会改变 这个怎么办

**Comment by tychxn** [comment]
没问题的，这些参数都不是一次性的

**Comment by jy024929** [comment]
原来如此，测试过下单确实是不影响的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tychxn"<notifications@github.com&gt;; 
发送时间: 2020年2月11日(星期二) 晚上10:03
收件人: "tychxn/jd-assistant"<jd-assistant@noreply.github.com&gt;; 
抄送: "玛法里奥 怒风"<305977338@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tychxn/jd-assistant] risk_control 这个参数每次刷新页面后都会改变 (#101)




没问题的，这些参数都不是一次性的

**Comment by jy024929** [comment]
还有个问题要咨询下，查到有货，下单后没货，东西一直滞留购物车，这个怎么办，程序继续运行，早上起来，一大堆购物车

**Comment by tychxn** [comment]
没有问题的这个，程序到时候会自动判断购物车情况进行处理

**Comment by jy024929** [comment]
谢谢，不过今天发现了，程序结束了，但是没有下单成功，东西留在购物车，有没有办法程序结束了，不要自动关闭，停留在那里，让我看看到底哪出错了？

**Comment by Oppswhite** [comment]
> 谢谢，不过今天发现了，程序结束了，但是没有下单成功，东西留在购物车，有没有办法程序结束了，不要自动关闭，停留在那里，让我看看到底哪出错了？

文件目录有log，可以自己分析

**Comment by jy024929** [comment]
> > 谢谢，不过今天发现了，程序结束了，但是没有下单成功，东西留在购物车，有没有办法程序结束了，不要自动关闭，停留在那里，让我看看到底哪出错了？
> 
> 文件目录有log，可以自己分析

谢谢啊
