### ISSUE TITLE
config.ini中eid与fp不一定存在

### ISSUE THREAD

**Issue by YLaido** [tychxn/jd-assistant#102]
多次测试账号并没有`eid`和`fp`，只有`trackId`和`riskControl`，只填后两个并不影响下单。

**Comment by cntink** [comment]
找个有货的商品就可以获取eid和fp

**Comment by YLaido** [comment]
就是下单有货的，测试了不填这两个也能提交订单

cntink <notifications@github.com>于2020年2月12日 周三22:36写道：

**Comment by tychxn** [comment]
这两个参数对下单的影响确实比较难分析，因为页面上相关的js代码被压缩加密了，我建议如果能查出来还是加上
