### ISSUE TITLE
请问地址是在哪设置的？为什么有个地址我都给删了下的订单还是往那送？

### ISSUE THREAD

**Issue by EnjoyColin** [tychxn/jd-assistant#106]

**Comment by iclouding** [comment]
同问，我的是京东的默认地址，不知道怎么修改

**Comment by EnjoyColin** [comment]
> 同问，我的是京东的默认地址，不知道怎么修改

我之后发现问题了。地址应该是取决于你往config.ini里填的东西。所以要想修改地址大概是得重新整一个订单，改好地址后再在订单页面获取相关数据。
