### ISSUE TITLE
购物车被清空了，好难受。

### ISSUE THREAD

**Issue by HGladiator** [tychxn/jd-assistant#110]
为什么不在wiki中提醒我，上来看着wiki直接跑程序，结果出现了购物车已清空，我直接傻眼了。我好难受，为什么你要这样伤害我！为什么不提醒我。上万的star结果还是这样伤害我！

**Comment by ShmilyChen** [comment]
```
from jd_assistant import Assistant

if __name__ == '__main__':
    asst = Assistant()      # 初始化
    asst.login_by_QRcode()  # 扫码登陆
    asst.clear_cart()       # 清空购物车（可选）
    asst.add_item_to_cart(sku_ids='100001324422')  # 根据商品id添加购物车（可选）
    asst.submit_order()     # 直接提交订单
```
看到了吗，清空购物车（可选）

**Comment by HGladiator** [comment]
```
@ShmilyChen  if __name__ == '__main__':
    """
    重要提示：此处为示例代码之一，请移步下面的链接查看使用教程👇
    https://github.com/tychxn/jd-assistant/wiki/1.-%E4%BA%AC%E4%B8%9C%E6%8A%A2%E8%B4%AD%E5%8A%A9%E6%89%8B%E7%94%A8%E6%B3%95
    """

    asst = Assistant()  # 初始化
    asst.login_by_QRcode()  # 扫码登陆
    asst.clear_cart() 
```
我今天下午下载的，我的是这样子的。
@ShmilyChen

**Comment by HGladiator** [comment]
打电话给vip客服说了，不能恢复，

**Comment by zaiweijian** [comment]
只是清空购物车，有啥影响嘛

**Comment by ShmilyChen** [comment]
"""
    重要提示：此处为示例代码之一，请移步下面的链接查看使用教程👇
    https://github.com/tychxn/jd-assistant/wiki/1.-%E4%BA%AC%E4%B8%9C%E6%8A%A2%E8%B4%AD%E5%8A%A9%E6%89%8B%E7%94%A8%E6%B3%95
    """

**Comment by HGladiator** [comment]
@ShmilyChen  我是定时抢购的，当然只看这个3.2.1 定时执行抢购请求（常用），然后直接开mian.py ,开泡，就没有关注你说到其他情况。

**Comment by HGladiator** [comment]
@zaiweijian 我62个商品，都是看到各种公众号文章推荐的产品加购的，现在全没了，过去所有的收集全都没有了。已经难受到吃不下饭

**Comment by HGladiator** [comment]
@zaiweijian 我62个商品，都是看到各种公众号文章推荐的产品加购的，现在全没了，过去所有的收集全都没有了。已经难受到吃不下饭

**Comment by HaoweiCh** [comment]
@HGladiator 小心一下，多观察一下代码。不是有意针对你的购物车哈。也谢谢你跟进消息

**Comment by cntink** [comment]
京东我的足迹里就找回来了，难受什么。。。。。

**Comment by 838070166** [comment]
商品点点关注很难么，放购物车收藏商品？
