### ISSUE TITLE
京东预约抢购的需要卡点，有没有大神写个可以同步京东服务器时间的脚本？

### ISSUE THREAD

**Issue by zaiweijian** [tychxn/jd-assistant#111]
。。。

**Comment by tychxn** [comment]
其实我也想知道在哪里能看到京东服务器的时间

**Comment by HaoweiCh** [comment]
容器里面调时间早当前时间2到3秒，这样提前点提交请求有没有作用？

**Comment by zaiweijian** [comment]
> 其实我也想知道在哪里能看到京东服务器的时间

http://www.0818tuan.com/xbhd/320003.html

**Comment by cnlike** [comment]
> 其实我也想知道在哪里能看到京东服务器的时间
> 
> http://www.0818tuan.com/xbhd/320003.html
这个只能精确到秒，还有就是京东的不同服务器时间是不完全同步的，即使是同一个URL。

**Comment by ccymail** [comment]
> > 其实我也想知道在哪里能看到京东服务器的时间
> 
> http://www.0818tuan.com/xbhd/320003.html

你好,这个脚本我执行报错 js 类型不对 ,请问什么原因?
