### ISSUE TITLE
定时抢购失败

### ISSUE THREAD

**Issue by 2010dainifei** [tychxn/jd-assistant#113]
记不清哪个QQ是你了，干脆你给写在这吧
![image](https://user-images.githubusercontent.com/60343206/74832990-852e0c80-5353-11ea-9984-04fffa5b99ab.png)

这个是失败的返回信息。
加车成功。但是无法下单，应该是勾选商品信息的代码没有生效。

**Comment by tychxn** [comment]
参考 https://github.com/tychxn/jd-assistant/issues/108
