### ISSUE TITLE
关于口罩预约然后秒杀

### ISSUE THREAD

**Issue by zhou-xiaojun** [tychxn/jd-assistant#114]
我改了整合了一下代码,发现时间的设定才是最大的问题啊,
不然就按当前时间设定,口罩基本没戏了.
因为测试条件太差一天就测那么一次.
这是我昨天晚上测的效果,返回的是没有抢到.证明代码是走的通的吧,~
希望大佬来帮我看一下是不是走通了,时间方面也帮忙提些意见.谢谢
<img width="1140" alt="WX20200220-050414@2x" src="https://user-images.githubusercontent.com/61015382/74876490-baac1780-539e-11ea-8210-3c83978a1150.png">

**Comment by zaiweijian** [comment]
01秒才获取到链接，这个是问题所在

**Comment by zhou-xiaojun** [comment]
@zaiweijian 
我刚设置也0.8秒也能正常获取.估计0.6也行.可惜一天只能尝试一次,
今天的测试结果也是2秒完成整个流程.但还是
抢购失败，返回信息: {'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90008, 'skuId': 0, 'success': False}
我很怀疑到底有没有这个商品的....还是真的就自己网速跟不上...
说实话2秒内完成整个流程.普通用户浏览器渲染也要这个时间吧.       :(

**Comment by zaiweijian** [comment]
0.8秒只能抢个寂寞

**Comment by zhou-xiaojun** [comment]
@zaiweijian 
这个100011385146口罩就是在搞心态.
评论区正常用户还评论能抢到.我都傻了.
而且基本是plus会员.

**Comment by JannisHan** [comment]
> 我改了整合了一下代码,发现时间的设定才是最大的问题啊,
> 不然就按当前时间设定,口罩基本没戏了.
> 因为测试条件太差一天就测那么一次.
> 这是我昨天晚上测的效果,返回的是没有抢到.证明代码是走的通的吧,~
> 希望大佬来帮我看一下是不是走通了,时间方面也帮忙提些意见.谢谢
> <img alt="WX20200220-050414@2x" width="1140" src="https://user-images.githubusercontent.com/61015382/74876490-baac1780-539e-11ea-8210-3c83978a1150.png">

老哥，你是不是用的mac，mac的时间和北京时间不同步，差1-2秒，把时间服务器改成美洲就可以了

**Comment by zhou-xiaojun** [comment]
@JannisHan 卧槽,老哥,设置好了.还真是...我刚转用mac没多久,就感觉一直都差1-2秒....谢了啊

**Comment by zaiweijian** [comment]
> @JannisHan 卧槽,老哥,设置好了.还真是...我刚转用mac没多久,就感觉一直都差1-2秒....谢了啊

没屌用，windows也是慢一秒

**Comment by DennisWong** [comment]
请问下你改的代码commit了嘛，我看你fork的仓库好像没有修改后的代码

**Comment by Funnyang** [comment]
可否共享一下代码啊？晚上用，下周开工了😂

**Comment by zhou-xiaojun** [comment]
有个新的skuid,也是预约再抢购的口罩.抢到了.我傻了都
时间还是一样的问题,要微调.我这次纯碎幸运,,过了1秒半才开始抢..也抢到了
晚点我commit到fork吧.
<img width="573" alt="WX20200222-192207@2x" src="https://user-images.githubusercontent.com/61015382/75091477-ac314c00-55a8-11ea-9a6a-b469a8eb1ad8.png">

**Comment by Funnyang** [comment]
@zhou-xiaojun commit 吧 时间不是问题，我写个1秒的循环就OK了，明早有两个可以抢，今晚手动抢没抢到😭

**Comment by Lasx** [comment]
> 有个新的skuid,也是预约再抢购的口罩.抢到了.我傻了都
> 时间还是一样的问题,要微调.我这次纯碎幸运,,过了1秒半才开始抢..也抢到了
> 晚点我commit到fork吧.
> <img alt="WX20200222-192207@2x" width="573" src="https://user-images.githubusercontent.com/61015382/75091477-ac314c00-55a8-11ea-9a6a-b469a8eb1ad8.png">

老哥 ，下周裸奔与否就看你的代码了。

**Comment by yangkang55** [comment]
> 有个新的skuid,也是预约再抢购的口罩.抢到了.我傻了都
> 时间还是一样的问题,要微调.我这次纯碎幸运,,过了1秒半才开始抢..也抢到了
> 晚点我commit到fork吧.
> <img alt="WX20200222-192207@2x" width="573" src="https://user-images.githubusercontent.com/61015382/75091477-ac314c00-55a8-11ea-9a6a-b469a8eb1ad8.png">

方便提交下代码么

**Comment by hero5512** [comment]
大神，方便共享下代码么

**Comment by congjinruo** [comment]
wow，@zhou-xiaojun 看到你的commit了，感谢哦
