### ISSUE TITLE
订单提交失败, 错误码：600158，好多这个错误

### ISSUE THREAD

**Issue by PHCSJC** [tychxn/jd-assistant#115]
这是误报呢？还是被别人抢了啊？

**Comment by tychxn** [comment]
参考 https://github.com/tychxn/jd-assistant/issues/108

**Comment by PHCSJC** [comment]
可是我这个不是抢购啊

**Comment by zaiweijian** [comment]
无货嘛？可能是脚本监控库存出错了，实际没货但是脚本显示有货，这时候下单肯定不成功
