### ISSUE TITLE
eid fp 值获取不到了，是不是jd给隐藏了？

### ISSUE THREAD

**Issue by leonvxe** [tychxn/jd-assistant#116]
网页源文件也搜不到
var eid = $('#eid').val();
var fp = $('#fp').val();
var trackId = getTakId();
var riskControl = $('#riskControl').val();
console.log(`eid = ${eid}\nfp = ${fp}\ntrack_id = ${trackId}\nrisk_control = ${riskControl}`);
这个也没有结果
有其他获取方式吗

**Comment by LixOx** [comment]
> 网页源文件也搜不到
> var eid = $('#eid').val();
> var fp = $('#fp').val();
> var trackId = getTakId();
> var riskControl = $('#riskControl').val();
> console.log(`eid = ${eid}\nfp = ${fp}\ntrack_id = ${trackId}\nrisk_control = ${riskControl}`);
> 这个也没有结果
> 有其他获取方式吗

任意加一件商品到购物车，点击【去结算】，然后f12，在console输入以上代码就能获取。源码wiki上有说明的。

**Comment by congjinruo** [comment]
是这样，你必须从网页上添加商品，然后再去购物车结算，你在手机上加入购物车，然后结算eid和fp时空的

**Comment by LixOx** [comment]
谢谢

Kuai <notifications@github.com> 于2020年2月24日周一 上午10:00写道：

**Comment by FPanda** [comment]
macOS safari 尝试直接在网页上操作，依然没有eid和fp。暂时在代码里屏蔽了检查，试了一下普通下单没有问题，目前在有优惠券的情况也没有遇到问题。

**Comment by yao8433** [comment]
> macOS safari 尝试直接在网页上操作，依然没有eid和fp。暂时在代码里屏蔽了检查，试了一下普通下单没有问题，目前在有优惠券的情况也没有遇到问题。

我也碰到同样问题没有eid和fp，有解决方法了么

**Comment by QJesus** [comment]
> > macOS safari 尝试直接在网页上操作，依然没有eid和fp。暂时在代码里屏蔽了检查，试了一下普通下单没有问题，目前在有优惠券的情况也没有遇到问题。
> 
> 我也碰到同样问题没有eid和fp，有解决方法了么

windows10 + chrome 可以获取到
