### ISSUE TITLE
预约抢购一共经过5个页面，每个页面有设置cookie，哪个页面访问能省略啊

### ISSUE THREAD

**Issue by ColoPaul** [tychxn/jd-assistant#125]
1、https://itemko.jd.com/itemShowBtn?callback=jQuery1535663&skuId=100011621642&from=pc&_=1583064010850，根据json获取抢购地址，新增了cookie
2、https://divide.jd.com/user_routing?skuId=100011621642&sn=02c6389498fefeded8595bcf4d0d4508&from=pc，这个是上一步获取到的抢购地址
3、上一步302，跳转到这个页面：https://marathon.jd.com/captcha.html?from=pc&skuId=100011621642&sn=02c6389498fefeded8595bcf4d0d4508，这个页面有新增cookie
4、订单结算页面
5、订单提交按钮，https://marathon.jd.com/seckillnew/orderService/pc/submitOrder.action?skuId=100011621642

几乎每个页面都有新增修改cookie，这几步到底能不能省，因为我现在就没有一次抢到过，我几乎都是500毫秒内就能获取到抢购地址，1秒多一点提交订单，但都是失败

我想问有抢到订单的各位，是按照项目的代码，没修改过代码抢到的么？还是中间有添加操作呢。因为按照旧有的代码，好像没有访问第三步的地址啊，也就会漏了第三步添加的cookie了

**Comment by dnovelty** [comment]
&emsp;&emsp;可以直接执行第5步。抢不到是真的没抢到(应该是京东其他控制因素，或许纯粹没抢到)。因为我就是只执行第5步抢到过商品。
&emsp;&emsp;不过我后来的秒杀代码增加了多线程方式，一个线程尽管执行第5步，另一个线程执行第1步，这样做的目的我纯粹是为了判断这个商品是不是真的秒杀商品。因为有些商品按钮写着《立即抢购》,结果一按却是加入到购物车😓。所以我加个线程，如果发现是普通购物模式就停掉那个抢购线程，执行普通购物下单。

**Comment by ColoPaul** [comment]
>   可以直接执行第5步。抢不到是真的没抢到(应该是京东其他控制因素，或许纯粹没抢到)。因为我就是只执行第5步抢到过商品。
>   不过我后来的秒杀代码增加了多线程方式，一个线程尽管执行第5步，另一个线程执行第1步，这样做的目的我纯粹是为了判断这个商品是不是真的秒杀商品。因为有些商品按钮写着《立即抢购》,结果一按却是加入到购物车。所以我加个线程，如果发现是普通购物模式就停掉那个抢购线程，执行普通购物下单。

那你其实抢购流程就是一个
线程1：访问itemko.jd.com/itemShowBtn获取抢购地址，获取抢购地址那个步骤，你怎么判断其实是加入购物车操作？
线程2：只执行submit_seckill_order这个步骤了对吧。

**Comment by dnovelty** [comment]
> > 可以直接执行第5步。抢不到是真的没抢到(应该是京东其他控制因素，或许纯粹没抢到)。因为我就是只执行第5步抢到过商品。
> >   不过我后来的秒杀代码增加了多线程方式，一个线程尽管执行第5步，另一个线程执行第1步，这样做的目的我纯粹是为了判断这个商品是不是真的秒杀商品。因为有些商品按钮写着《立即抢购》,结果一按却是加入到购物车。所以我加个线程，如果发现是普通购物模式就停掉那个抢购线程，执行普通购物下单。
> 
> 那你其实抢购流程就是一个
> 线程1：访问itemko.jd.com/itemShowBtn获取抢购地址，获取抢购地址那个步骤，你怎么判断其实是加入购物车操作？线程1获取到抢购地址以后，你有request这个地址嘛？
> 线程2：只执行submit_seckill_order这个步骤了对吧。
> 比如抢购时间是8点，你这两个线程是8点一到，同时跑么？

&emsp;&emsp; * 加入购物车操作，它返回的地址域名是cart.jd.com。有做request操作，并且这个request和那个抢购线程用的同一个session。(其实这个request操作可有可无吧，我最开始写的抢购根本没有去调用itemShowBtn接口)
&emsp;&emsp; * 线程2只执行submit_seckill_order。
&emsp;&emsp; * 一到8点，两个线程同时跑。

**Comment by ColoPaul** [comment]
> > > 可以直接执行第5步。抢不到是真的没抢到(应该是京东其他控制因素，或许纯粹没抢到)。因为我就是只执行第5步抢到过商品。
> > >   不过我后来的秒杀代码增加了多线程方式，一个线程尽管执行第5步，另一个线程执行第1步，这样做的目的我纯粹是为了判断这个商品是不是真的秒杀商品。因为有些商品按钮写着《立即抢购》,结果一按却是加入到购物车。所以我加个线程，如果发现是普通购物模式就停掉那个抢购线程，执行普通购物下单。
> > 
> > 
> > 那你其实抢购流程就是一个
> > 线程1：访问itemko.jd.com/itemShowBtn获取抢购地址，获取抢购地址那个步骤，你怎么判断其实是加入购物车操作？线程1获取到抢购地址以后，你有request这个地址嘛？
> > 线程2：只执行submit_seckill_order这个步骤了对吧。
> > 比如抢购时间是8点，你这两个线程是8点一到，同时跑么？
> 
>    * 加入购物车操作，它返回的地址域名是cart.jd.com。有做request操作，并且这个request和那个抢购线程用的同一个session。(其实这个request操作可有可无吧，我最开始写的抢购根本没有去调用itemShowBtn接口)
>    * 线程2只执行submit_seckill_order。
>    * 一到8点，两个线程同时跑。

了解了，谢谢！

**Comment by zaiweijian** [comment]
>   可以直接执行第5步。抢不到是真的没抢到(应该是京东其他控制因素，或许纯粹没抢到)。因为我就是只执行第5步抢到过商品。
>   不过我后来的秒杀代码增加了多线程方式，一个线程尽管执行第5步，另一个线程执行第1步，这样做的目的我纯粹是为了判断这个商品是不是真的秒杀商品。因为有些商品按钮写着《立即抢购》,结果一按却是加入到购物车。所以我加个线程，如果发现是普通购物模式就停掉那个抢购线程，执行普通购物下单。

请问，你的代码抢到过几次了？那种晚上8点的3q和袋鼠可以抢吗？
