### ISSUE TITLE
有没有抢到的？各位

### ISSUE THREAD

**Issue by heewq** [tychxn/jd-assistant#126]

**Comment by catninelife** [comment]
看wiki，仅供娱乐 哈哈

**Comment by mzs0207** [comment]
有抢到

**Comment by bin1129** [comment]
今天3个账户都抢到了稳健口罩，我都惊了

**Comment by ColoPaul** [comment]
> 今天3个账户都抢到了稳健口罩，我都惊了

skuid多少啊

**Comment by ColoPaul** [comment]
我今天也抢到了弓立医疗的口罩

**Comment by D68321** [comment]
我说自己用手动的怎么都抢不到，原来高手都在用这个啊

**Comment by w591213060** [comment]
> 今天3个账户都抢到了稳健口罩，我都惊了
qq多少啊，大神，这个咋使用呢？

**Comment by heewq** [comment]
> 今天3个账户都抢到了稳健口罩，我都惊了

请问[抢购链接获取失败，100011521400不是抢购商品或抢购页面暂未刷新，1秒后重试]这个问题怎么解决的，改代码么？

**Comment by ColoPaul** [comment]
> > 今天3个账户都抢到了稳健口罩，我都惊了
> 
> 请问[抢购链接获取失败，100011521400不是抢购商品或抢购页面暂未刷新，1秒后重试]这个问题怎么解决的，改代码么？

这个要么你没预约，要么你预约了，还没到时间，就会报这个错

**Comment by ColoPaul** [comment]
> > > 今天3个账户都抢到了稳健口罩，我都惊了
> > 
> > 
> > skuid多少啊
> 
> 66050948081

你是调用哪个方法抢的，是_exec_seckill抢购么，还是普通下单流程，哪个过程

**Comment by zhangheng8687** [comment]
> 今天3个账户都抢到了稳健口罩，我都惊了

能教一下使用教程吗？有偿

**Comment by zhnnix** [comment]
@bin1129 emmmm  三个账户 是怎么做到的。。。。
