### ISSUE TITLE
秒杀的地址如何修改

### ISSUE THREAD

**Issue by ecling** [tychxn/jd-assistant#128]
获取的默认地址吗？

修改过默认地址也是无效的，还是原来的地址下单，求教如何才能修改

**Comment by springbrother007** [comment]
去jd里修改你的默认收货地址

**Comment by linechina** [comment]
下单里面要增加get_checkout_page_detail 否则默认地址不会生效 ，或者你改了默认地址之后 自己随便下一单，然后再进行秒杀
