### ISSUE TITLE
提示点击抢购按钮下单是什么情况呢？

### ISSUE THREAD

**Issue by ljkrock** [tychxn/jd-assistant#129]
提示点击抢购按钮下单是什么情况呢？

**Comment by tychxn** [comment]
莫非又更新了…
调用的函数和日志贴上来看一下

**Comment by ljkrock** [comment]
> 莫非又更新了…
> 调用的函数和日志贴上来看一下

我今天在抢一次试下，还报这个我截下图

**Comment by tychxn** [comment]
文件夹里面有 .log 文件，可以直接看一下

**Comment by ljkrock** [comment]
> 文件夹里面有 .log 文件，可以直接看一下

订单提交失败, 错误码：600126, 返回信息：*** 正在参与抢购活动，请重新回到商品详情页，使用“立即抢购”进行购买

前几天你更新了代码，是不是处理了这个问题了

**Comment by uouuou** [comment]
> 文件夹里面有 .log 文件，可以直接看一下

大佬，可否请教一下抢购模式下能不能使用BestCoupon

**Comment by tychxn** [comment]
> > 文件夹里面有 .log 文件，可以直接看一下
> 
> 大佬，可否请教一下抢购模式下能不能使用BestCoupon

一直没有空研究抢购模式优惠券问题，你要不抓包和代码中的post参数比对一下

**Comment by uouuou** [comment]
> > > 文件夹里面有 .log 文件，可以直接看一下
> > 
> > 
> > 大佬，可否请教一下抢购模式下能不能使用BestCoupon
> 
> 一直没有空研究抢购模式优惠券问题，你要不抓包和代码中的post参数比对一下

这个很尴尬，抢购的时候都是争分夺秒，不知道怎么样才能进行测试
