### ISSUE TITLE
是否可以会添加多商品监控？

### ISSUE THREAD

**Issue by linuxsky** [tychxn/jd-assistant#13]
多商品 某一时刻 下单抢购  是否会添加？ 因为某一时刻可能会选择多个商品，或者监控 多个商品到货 下单

**Comment by tychxn** [comment]
同时监控多个商品的库存，当他们都有货的时候，下成一个订单吗？这么理解有没有问题

**Comment by linuxsky** [comment]
> 同时监控多个商品的库存，当他们都有货的时候，下成一个订单吗？这么理解有没有问题 @linuxsky

对的，就是比如我可以列入一个商品列表，哪个有货了就自动下单不必要都凑到一起。
另外一个题外话，大神考不考虑 加入小米商城的抢购呢？

**Comment by tychxn** [comment]
- 如果的确有这种多商品的需求，我可以后面试着加一下
- 关于题外话：很久没有研究过小米商城的抢购机制了，如果能提供几份抢购数据包的话，可以研究一下哈哈～～

**Comment by linuxsky** [comment]
> * 如果的确有这种多商品的需求，我可以后面试着加一下
> * 关于题外话：很久没有研究过小米商城的抢购机制了，如果能提供几份抢购数据包的话，可以研究一下哈哈～～

嗯嗯我是有这个方面需求，因为经常抢购一些新品可能会监控几个产品。是不是大众需求还不确定

好啊，那等抢购时候我用 chars 抓一个。只不过抢不到。。。。。

**Comment by tychxn** [comment]
抢购成功或者失败其实没关系，只要能获取到提交到服务器的数据信息即可～～

**Comment by linuxsky** [comment]
> 抢购成功或者失败其实没关系，只要能获取到提交到服务器的数据信息即可～～

抓了一组包，怎么啊给你呢？ 邮箱？

**Comment by tychxn** [comment]
tychxn@gmail.com

**Comment by DonYeung** [comment]
大神好，我觉得可以加上一个需求，
方法：add_item_to_cart（添加到购物车 ）、submit_order（直接提交订单）、submit_order_by_stock（当商品有库存时提交订单）、exec_seckill_by_time（定时抢购）等一些方法，
可以把各个方法的商品id弄成多个，以多个id的方式进行循环，全部满足条件后再提交订单。
例如：submit_order_by_stock （当商品有库存时提交订单）
当有多个商品需要进行同时购买时，可以将多个商品的id给到submit_order_by_stock方法，然后等这几个商品的都有库存时提交订单。
谢谢大神的付出！！

**Comment by tychxn** [comment]
完成多商品的库存监控和下单功能。
