### ISSUE TITLE
崩溃：raise JSONDecodeError("Expecting value", s, err.value) from None

### ISSUE THREAD

**Issue by QJesus** [tychxn/jd-assistant#130]
```text
2020-03-13 20:00:01,232 INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100006394713&sn=f312ffa28ce4d522b295414989499520&from=pc
ction submit_seckill_order.
  if self.submit_seckill_order(sku_id, num):
D:\jd-assistant-copy\jd_assistant.py:1248: DeprecationWarning: Call to deprecated function _gen_seckill_order_data.
  self.seckill_order_data[sku_id] = self._gen_seckill_order_data(sku_id, num)
D:\jd-assistant-copy\jd_assistant.py:1192: DeprecationWarning: Call to deprecated function _get_seckill_init_info.
  self.seckill_init_info[sku_id] = self._get_seckill_init_info(sku_id)
null
Traceback (most recent call last):
  File ".\seckill.py", line 17, in <module>
    asst.exec_seckill(sku_id=sku_id, retry=5, interval=0.01, num=1)
  File "D:\jd-assistant-copy\util.py", line 208, in new_func
    return func(*args, **kwargs)
  File "D:\jd-assistant-copy\jd_assistant.py", line 1307, in exec_seckill
    if self.submit_seckill_order(sku_id, num):
  File "D:\jd-assistant-copy\util.py", line 208, in new_func
    return func(*args, **kwargs)
  File "D:\jd-assistant-copy\jd_assistant.py", line 1248, in submit_seckill_order    
    self.seckill_order_data[sku_id] = self._gen_seckill_order_data(sku_id, num)
  File "D:\jd-assistant-copy\util.py", line 208, in new_func
    return func(*args, **kwargs)
  File "D:\jd-assistant-copy\jd_assistant.py", line 1192, in _gen_seckill_order_data 
    self.seckill_init_info[sku_id] = self._get_seckill_init_info(sku_id)
  File "D:\jd-assistant-copy\util.py", line 208, in new_func
    return func(*args, **kwargs)
  File "D:\jd-assistant-copy\jd_assistant.py", line 1180, in _get_seckill_init_info  
    return parse_json(resp.text)
  File "D:\jd-assistant-copy\util.py", line 123, in parse_json
    return json.loads(s[begin:end])
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ColoPaul** [comment]
自己加try catch进行错误检测

**Comment by tychxn** [comment]
> ```
> 2020-03-13 20:00:01,232 INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100006394713&sn=f312ffa28ce4d522b295414989499520&from=pc
> ction submit_seckill_order.
>   if self.submit_seckill_order(sku_id, num):
> D:\jd-assistant-copy\jd_assistant.py:1248: DeprecationWarning: Call to deprecated function _gen_seckill_order_data.
>   self.seckill_order_data[sku_id] = self._gen_seckill_order_data(sku_id, num)
> D:\jd-assistant-copy\jd_assistant.py:1192: DeprecationWarning: Call to deprecated function _get_seckill_init_info.
>   self.seckill_init_info[sku_id] = self._get_seckill_init_info(sku_id)
> null
> Traceback (most recent call last):
>   File ".\seckill.py", line 17, in <module>
>     asst.exec_seckill(sku_id=sku_id, retry=5, interval=0.01, num=1)
>   File "D:\jd-assistant-copy\util.py", line 208, in new_func
>     return func(*args, **kwargs)
>   File "D:\jd-assistant-copy\jd_assistant.py", line 1307, in exec_seckill
>     if self.submit_seckill_order(sku_id, num):
>   File "D:\jd-assistant-copy\util.py", line 208, in new_func
>     return func(*args, **kwargs)
>   File "D:\jd-assistant-copy\jd_assistant.py", line 1248, in submit_seckill_order    
>     self.seckill_order_data[sku_id] = self._gen_seckill_order_data(sku_id, num)
>   File "D:\jd-assistant-copy\util.py", line 208, in new_func
>     return func(*args, **kwargs)
>   File "D:\jd-assistant-copy\jd_assistant.py", line 1192, in _gen_seckill_order_data 
>     self.seckill_init_info[sku_id] = self._get_seckill_init_info(sku_id)
>   File "D:\jd-assistant-copy\util.py", line 208, in new_func
>     return func(*args, **kwargs)
>   File "D:\jd-assistant-copy\jd_assistant.py", line 1180, in _get_seckill_init_info  
>     return parse_json(resp.text)
>   File "D:\jd-assistant-copy\util.py", line 123, in parse_json
>     return json.loads(s[begin:end])
>   File "C:\Users\ABC\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
>     return _default_decoder.decode(s)
>   File "C:\Users\ABC\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "C:\Users\ABC\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```

建议在`jd_assistant.py` line 1179 行添加 `logger.info(resp.text)`，看看返回数据是不是json结构的，我这里没法复现这个问题

**Comment by QJesus** [comment]
修改 util.py 第 122 行

``` python
def parse_json(s):
    begin = s.find('{')
    end = s.rfind('}') + 1
    return json.loads('{}' if s[begin:end] == '' else s[begin:end])
```
