### ISSUE TITLE
risk_control

### ISSUE THREAD

**Issue by BornInDecember** [tychxn/jd-assistant#137]
risk_control =
为空，怎么处理啊？

**Comment by littlecangbaby** [comment]
我也是

**Comment by OKCup** [comment]
一样

**Comment by luyehui** [comment]
我也是同样的问题

**Comment by Shuiyu007** [comment]
我也是，我写了个0，不影响下单

**Comment by Thenck** [comment]
现在 trackId也没了

**Comment by 0123cf** [comment]
> 现在 trackId也没了

function getCookie(cname)
{
  var name = cname + "=";
  var ca = document.cookie.split(';');
  for(var i=0; i<ca.length; i++) 
  {
    var c = ca[i].trim();
    if (c.indexOf(name)==0) return c.substring(name.length,c.length);
  }
  return "";
}

var eid = $('#eid').val();
var fp = $('#fp').val();
var trackId = getCookie('TrackID');
var riskControl = $('#riskControl').val();
console.log(`eid = ${eid}\nfp = ${fp}\ntrack_id = ${trackId}\nrisk_control = ${riskControl}`);

**Comment by Fanchao-Qi** [comment]
edi fp 还有riskControl似乎都是undefined
