### ISSUE TITLE
riskControl 为空

### ISSUE THREAD

**Issue by Crazy-han** [tychxn/jd-assistant#138]
var eid = $('#eid').val();
var fp = $('#fp').val();
var trackId = getTakId();
var riskControl = $('#riskControl').val();
console.log(`eid = ${eid}\nfp = ${fp}\ntrack_id = ${trackId}\nrisk_control = ${riskControl}`);

eid 、 fp 、 track_id 都可以获取到
risk_control 未能成功获取

**Comment by cfmj** [comment]
请问如何获取risk_control
