### ISSUE TITLE
定时下单过程中可能需要添加购物车动作

### ISSUE THREAD

**Issue by linuxsky** [tychxn/jd-assistant#14]
在定时下单 或者有货下单流程中 如果本身商品处于无货状态是不能添加到购物车的，拿着时候在 轮训货物状态或者时间的时候时不时应该 在有活或者到时间时候在考虑添加购物车动作呢？

**Comment by tychxn** [comment]
> 如果本身商品处于无货状态是不能添加到购物车的

不是这样的，在商品没货的时候我们在网页上看无法加购物车，但是使用代码可以加入购物车。
如果时间到或者有货才进行加购物车操作，我考虑会慢一拍。

**Comment by linuxsky** [comment]
我今天看到有个 商品 mate20 他处于没货状态，然后加购物车失败，应该是属于抢购商品 没法加购物车。现在我看预约商品能用了？

**Comment by tychxn** [comment]
商品id给我发一下看看

现在有两种模式：
- 普通加购物车下单模式
- 抢购模式（无法加入购物车）

抢购模式的话大部分都需要先预约，然后抢购，无法加入购物车。
抢购模式的代码是有了，对应`exec_seckill`方法，之前测试魅族16的抢购没有问题，但还是不太确定。

**Comment by tychxn** [comment]
好的，我改改，搞成定时的~

**Comment by springbrother007** [comment]
楼主大才
低调低调，低调使得万年船
建议仅提供全局思路和部分代码，关键部分抽离，不然。。。。

**Comment by tychxn** [comment]
抢购商品的代码已更新，可以定时抢购，使用的是`https://item.jd.com/100001036246.html`这个商品做的测试。
![image](https://user-images.githubusercontent.com/29301320/49234335-d1312080-f432-11e8-97b8-99eb5a1784b0.png)
@linuxsky 
@springbrother007 感谢建议，暂时还是不考虑抽离代码哈～
