### ISSUE TITLE
VM51280:3 Uncaught ReferenceError: getTakId is not defined怎么处理

### ISSUE THREAD

**Issue by RideWind1** [tychxn/jd-assistant#145]
执行了下面代码之后报错VM51280:3 Uncaught ReferenceError: getTakId is not defined
var eid = $('#eid').val();
var fp = $('#fp').val();
var trackId = getTakId();
var riskControl = $('#riskControl').val();
console.log(`eid = ${eid}\nfp = ${fp}\ntrack_id = ${trackId}\nrisk_control = ${riskControl}`);

**Comment by kuangjy2** [comment]
可以尝试将getTakId()改成COOKIETRACK.getCookie("TrackID")

**Comment by SundayRX** [comment]
var eid = $('#eid').val();
var fp = $('#fp').val();
var trackId = $("#TrackID").val();
var riskControl = $('#riskControl').val();
console.log(`eid = ${eid}\nfp = ${fp}\ntrack_id = ${trackId}\nrisk_control = ${riskControl}`);

**Comment by cuishao-max** [comment]
我也遇到了，请问你解决了吗？同求解答

**Comment by bobcc4** [comment]
> var eid = $('#eid').val();
> var fp = $('#fp').val();
> var trackId = $("#TrackID").val();
> var riskControl = $('#riskControl').val();
> console.log(`eid = ${eid}\nfp = ${fp}\ntrack_id = ${trackId}\nrisk_control = ${riskControl}`);

报错 missing ) after argument list

**Comment by cuishao-max** [comment]
var eid = $('#eid').val();
var fp = $('#fp').val();
var trackId = $("#TrackID").val();
var riskControl = $('#riskControl').val();
console.log(`eid = ${eid}\nfp = ${fp}\ntrack_id = ${trackId}\nrisk_control = ${riskControl}`);

**Comment by cuishao-max** [comment]
最后一行的eid=之前和riskControl}之后少了`(Tab上面那个键)符号

**Comment by bobcc4** [comment]
> 最后一行的eid=之前和riskControl}之后少了`(Tab上面那个键)符号

谢谢，可以在console中运行，但是eid和fp和risk都为空，只有trackid有

**Comment by IsraelSuen** [comment]
所以到底是怎么回事

> > 最后一行的eid=之前和riskControl}之后少了`(Tab上面那个键)符号
> 
> 谢谢，可以在console中运行，但是eid和fp和risk都为空，只有trackid有

**Comment by luofeng0603** [comment]
> 所以到底是怎么回事
> 
> > > 最后一行的eid=之前和riskControl}之后少了`(Tab上面那个键)符号
> > 
> > 
> > 谢谢，可以在console中运行，但是eid和fp和risk都为空，只有trackid有

依然有这个问题，有人知道咋回事吗？
var eid = $('#eid').val();
var fp = $('#fp').val();
var trackId = getTakId();
var riskControl = $('#riskControl').val();
console.log(`eid = ${eid}\nfp = ${fp}\ntrack_id = ${trackId}\nrisk_control = ${riskControl}`);
Uncaught ReferenceError: getTakId is not defined

**Comment by Thenck** [comment]
应该是 风控系统升级 这个字段废弃了或者其他渠道获取

**Comment by ch77806492** [comment]
真的假的，刚刚想用，提示 getTakId() 错误，直接啥也获取不到

**Comment by Sunnie-Y** [comment]
var eid = $('#eid').val();
var fp = $('#fp').val();
var trackId = $("#TrackID").val();
var riskControl = $('#riskControl').val();
console.log(`eid = ${eid}\nfp = ${fp}\ntrack_id = ${trackId}\nrisk_control = ${riskControl}`);
这个可以

**Comment by baiyibing123** [comment]
> var eid = $('#eid').val();
> var fp = $('#fp').val();
> var trackId = $("#TrackID").val();
> var riskControl = $('#riskControl').val();
> console.log(`eid = ${eid}\nfp = ${fp}\ntrack_id = ${trackId}\nrisk_control = ${riskControl}`);
> 这个可以

也不可以

**Comment by royrx93** [comment]
> var eid = $('#eid').val();
> var fp = $('#fp').val();
> var trackId = $("#TrackID").val();
> var riskControl = $('#riskControl').val();
> console.log(`eid = ${eid}\nfp = ${fp}\ntrack_id = ${trackId}\nrisk_control = ${riskControl}`);
> 这个可以

这个得到是空的
