### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

### ISSUE THREAD

**Issue by delfws** [tychxn/jd-assistant#153]
为啥我执行pip install -r requirements.txt会报这个错误

error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

Running setup.py install for pycryptodome ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\system\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-acg3313w\\pycryptodome\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-acg3313w\\pycryptodome\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Administrator\AppData\Local\Temp\pip-record-jn_ot6pm\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\system\python\Include\pycryptodome'
         cwd: C:\Users\Administrator\AppData\Local\Temp\pip-install-acg3313w\pycryptodome\

**Comment by xiwuyun** [comment]
可以去安装whl版的cryptodome

**Comment by delfws** [comment]
好答案
