### ISSUE TITLE
想学这块的东西请指点下

### ISSUE THREAD

**Issue by whosudady** [tychxn/jd-assistant#156]
请问如果想学习自己业余开发这种东西，是只需要会python爬虫么，还需要学前端？？请指点哈啊

**Comment by bushnerd** [comment]
只会python估计不行，可能还要会写前端知识，不过通过python入了门，其他知识学起来应该也快吧。

**Comment by inorilzy** [comment]
> 请问如果想学习自己业余开发这种东西，是只需要会python爬虫么，还需要学前端？？请指点哈啊

前段不用会写，了解一点就行。选择器那里。
