### ISSUE TITLE
定时秒杀获取地址报错login =-1

### ISSUE THREAD

**Issue by hermit2018** [tychxn/jd-assistant#27]
https://marathon.jd.com/seckillnew/orderService/pc/init.action 报错login = -1

**Comment by tychxn** [comment]
谢谢，我明天查一下。

**Comment by tychxn** [comment]
hi, 

最近有点忙不好意思，我测试了一下，发现代码目前还是能正常抢购的。

- 所有抢购活动都要登陆后才能进行。
- 在定时秒杀时，如果出现获取不到抢购地址的情况，多数时因为抢购的商品为新产品，抢购地址JD后台还没有配置进去。一般新产品第一次发售时，抢购地址是在抢购的前几分钟才能获取到；如果是老产品，那么就是随时能够获取到了。
- `https://marathon.jd.com/seckillnew/orderService/pc/init.action`该链接是用于获取抢购提交订单时的初始化数据的，不是用于获取秒杀地址的。该链接对应的方法自动调用，无需手动调用。

如果还有问题，欢迎联系`tychxn@gmail.com`~

**Comment by hermit2018** [comment]
![1](https://user-images.githubusercontent.com/41882964/54334301-872a1e80-4660-11e9-9d4a-c55a731d7487.jpg)
这个报错是涉密原因啊

**Comment by tychxn** [comment]
请问你是修改过代码了吗？

`jd-assistant.py`文件第**930**行，
原来的代码是：https://github.com/tychxn/jd-assistant/blob/master/jd_assistant.py#L930
```python
default_address = init_info['addressList'][0]  # 默认地址dict
```

你的代码是：
```python
default_address = init_info['addressList'][1]  # 默认地址dict
```

**Comment by hermit2018** [comment]
的确改过了 因为init_info['addressList'][0]也是报错的这个 所以我改成了1 还是报错这个

**Comment by tychxn** [comment]
这个说明后台返回的地址信息为空，麻烦查一下是否将地址设置为默认地址。

**Comment by hermit2018** [comment]
应该是我传参有问题 ，我又试了遍可以了 谢谢大佬
