### ISSUE TITLE
电脑小白，查了N久教程终于安装完库，结果却打不开assistant和tools

### ISSUE THREAD

**Issue by q350976501** [tychxn/jd-assistant#3]
不知道是哪里出问题呢？
最好能有个使用指引
感谢

**Comment by q350976501** [comment]
main可以打开，但是登陆完就没了

**Comment by tychxn** [comment]
感谢使用，日后会加上使用指南。
现在还未添加定时或有货下单功能，能做的是登陆后直接下单，需要自己修改main函数中的商品id，并去除提交订单前面的注释符号。
