### ISSUE TITLE
抢购链接获取失败

### ISSUE THREAD

**Issue by hzq1995** [tychxn/jd-assistant#30]

**Comment by hzq1995** [comment]
现在的抢购商品也是得加入购物车，是因为现在抢购的方法变了么？

**Comment by tychxn** [comment]
最近好久没有关注了，请问最近有哪些可以抢购的，我抓包看一下。

**Comment by hzq1995** [comment]
这个是三小时以后的抢购 https://item.jd.com/100004601262.html
这个是正在抢购 https://item.jd.com/100003281995.html

**Comment by tychxn** [comment]
这些抢购商品的确跟之前不太一样了，感觉就跟普通商品下单流程一致，缺少了小米、华为手机的抢购还真缺点数据包。

**Comment by hzq1995** [comment]
是呀是呀~
