### ISSUE TITLE
找到 抢购下单的商品，数据包 足够更新代码吗？

### ISSUE THREAD

**Issue by zhnTrust** [tychxn/jd-assistant#39]
![2019-11-10_125107](https://user-images.githubusercontent.com/39142389/68539084-df185100-03b8-11ea-88fa-8a2b41a796a4.png)
商品链接: https://item.jd.com/35002778394.html

**Comment by tychxn** [comment]
这类商品点击`立即抢购`后会自动加入购物车结算，其实是`普通商品`，并不是抢购商品。

已更新wiki中使用文档：[区分商品类型](https://github.com/tychxn/jd-assistant/wiki/2.-%E5%8C%BA%E5%88%86%E5%95%86%E5%93%81%E7%B1%BB%E5%9E%8B#%E6%99%AE%E9%80%9A%E5%95%86%E5%93%81)

感谢～
