### ISSUE TITLE
京东支付接口

### ISSUE THREAD

**Issue by linechina** [tychxn/jd-assistant#43]
能不能做一个对指定订单的支付接口呀，使用京东支付就可以

**Comment by tychxn** [comment]
后续可以考虑这个，目前下单都还不是很稳定，还是登录网站手动支付吧～

**Comment by wyuzhi** [comment]
有货时购买一直报错

**Comment by tychxn** [comment]
> 有货时购买一直报错

麻烦贴一下你的使用代码，以及报错信息 @wyuzhi

**Comment by wyuzhi** [comment]
![1](https://user-images.githubusercontent.com/34329801/70773521-aa7e2780-1db2-11ea-85b6-a193a1004520.png)
![2](https://user-images.githubusercontent.com/34329801/70773538-b23dcc00-1db2-11ea-9cc9-55a06adaf839.png)

**Comment by tychxn** [comment]
@wyuzhi 收到，估计是京东接口变动，晚上查一下fix～

**Comment by tychxn** [comment]
@wyuzhi 京东查询库存接口变动，已fix.
