### ISSUE TITLE
无法使用 

### ISSUE THREAD

**Issue by z1027001** [tychxn/jd-assistant#46]
在安装requirements中的环境时便有错误提示  按教程修改了main.py后双击后一闪而过 因为本人没有学习python 所以恳请能有更详细一点的教学 或tg群QQ之类的也可以 万分感激

**Comment by Oppswhite** [comment]
安装时候的错误，你的cmd是管理员权限创建的吗

**Comment by Oppswhite** [comment]
> 在安装requirements中的环境时便有错误提示 按教程修改了main.py后双击后一闪而过 因为本人没有学习python 所以恳请能有更详细一点的教学 或tg群QQ之类的也可以 万分感激

安装时候的错误，你的cmd是管理员权限创建的吗

**Comment by z1027001** [comment]
> > 在安装requirements中的环境时便有错误提示 按教程修改了main.py后双击后一闪而过 因为本人没有学习python 所以恳请能有更详细一点的教学 或tg群QQ之类的也可以 万分感激
> 
> 安装时候的错误，你的cmd是管理员权限创建的吗

尝试用管理员cmd也不行  错误提示如下（部分）
 ERROR: Command errored out with exit status 1:
     command: 's:\python3.81\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-p20y0f01\\pycryptodome\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-p20y0f01\\pycryptodome\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-record-_r8qlvmw\install-record.txt' --single-version-externally-managed --compile --install-headers 's:\python3.81\Include\pycryptodome'
         cwd: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-p20y0f01\pycryptodome\
    Complete output (387 lines):
    running install
    running build
    running build_py
    creating build

**Comment by Oppswhite** [comment]
> > > 在安装requirements中的环境时便有错误提示 按教程修改了main.py后双击后一闪而过 因为本人没有学习python 所以恳请能有更详细一点的教学 或tg群QQ之类的也可以 万分感激
> > 
> > 
> > 安装时候的错误，你的cmd是管理员权限创建的吗
> 
> 尝试用管理员cmd也不行 错误提示如下（部分）
> ERROR: Command errored out with exit status 1:
> command: 's:\python3.81\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-p20y0f01\pycryptodome\setup.py'"'"'; **file**='"'"'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-p20y0f01\pycryptodome\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-record-_r8qlvmw\install-record.txt' --single-version-externally-managed --compile --install-headers 's:\python3.81\Include\pycryptodome'
> cwd: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-p20y0f01\pycryptodome
> Complete output (387 lines):
> running install
> running build
> running build_py
> creating build

作为使用者没遇见过，检查你的python版本，再不行手动安装环境？
https://www.python.org/ftp/python/3.5.4/python-3.5.4-amd64.exe

**Comment by z1027001** [comment]
好的我现在尝试------------------ 原始邮件 ------------------
发件人: "Oppswhite"<notifications@github.com>
发送时间: 2020年1月24日(星期五) 下午2:27
收件人: "tychxn/jd-assistant"<jd-assistant@noreply.github.com>;
抄送: "z1027001"<1027001766@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [tychxn/jd-assistant] 无法使用  (#46)


   
在安装requirements中的环境时便有错误提示 按教程修改了main.py后双击后一闪而过 因为本人没有学习python 所以恳请能有更详细一点的教学 或tg群QQ之类的也可以 万分感激
  
安装时候的错误，你的cmd是管理员权限创建的吗
  
尝试用管理员cmd也不行 错误提示如下（部分）
 ERROR: Command errored out with exit status 1:
 command: 's:\python3.81\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-p20y0f01\pycryptodome\setup.py'"'"'; file='"'"'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-p20y0f01\pycryptodome\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-record-_r8qlvmw\install-record.txt' --single-version-externally-managed --compile --install-headers 's:\python3.81\Include\pycryptodome'
 cwd: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-p20y0f01\pycryptodome
 Complete output (387 lines):
 running install
 running build
 running build_py
 creating build
  
作为使用者没遇见过，检查你的python版本，再不行手动安装环境？
 https://www.python.org/ftp/python/3.5.4/python-3.5.4-amd64.exe
 
&mdash;
