### ISSUE TITLE
venderId以及返回json格式改变

### ISSUE THREAD

**Issue by Thiasap** [tychxn/jd-assistant#47]
payload里venderId现在变得需要了，如果不提供这个参数，json会返回
```
{
	"StockState": 33,
	"area": {
		"townName": "",
		"provinceName": "北京",
		"cityName": "朝阳区",
		"success": true,
		"countyName": "三环以内"
	},
	"realSkuId": 100006176160,
	"choseSuit": [],
	"code": 1,
	"err": true,
	"PopType": 0,
	"ArrivalDate": null,
	"IsPurchase": false,
	"StockStateName": "有货",
	"rn": -1
}
```
然后会一直提交失败。
然后正常返回的json格式变了，当然也不一定是所有的都这样吧，我这里是看的id为100006176160的商品，这会导致的结果就是jd_assistant.py第437行找不到关键字StockState
```
{
	"stock": {
		"freshEdi": null,
		……
		"area": {
			"townName": "",
			"cityName": "朝阳区",
			"success": true,
			"provinceName": "北京",
			"countyName": "三环以内"
		},
		……
		"StockState": 34,
		"StockStateName": "无货",
		……
		"ArrivalDate": "",
		"v": "0"
	},
	"choseSuit": []
}
```
目前我在419行的payload里添加了商品venderId（好像就是店铺首页url的那串数字），然后在stock_state之前添加了resp_json = resp_json['stock']

**Comment by Oppswhite** [comment]
> payload里venderId现在变得需要了，如果不提供这个参数，json会返回
> 
> ```
> {
> 	"StockState": 33,
> 	"area": {
> 		"townName": "",
> 		"provinceName": "北京",
> 		"cityName": "朝阳区",
> 		"success": true,
> 		"countyName": "三环以内"
> 	},
> 	"realSkuId": 100006176160,
> 	"choseSuit": [],
> 	"code": 1,
> 	"err": true,
> 	"PopType": 0,
> 	"ArrivalDate": null,
> 	"IsPurchase": false,
> 	"StockStateName": "有货",
> 	"rn": -1
> }
> ```
> 
> 然后会一直提交失败。
> 然后正常返回的json格式变了，当然也不一定是所有的都这样吧，我这里是看的id为100006176160的商品，这会导致的结果就是jd_assistant.py第437行找不到关键字StockState
> 
> ```
> {
> 	"stock": {
> 		"freshEdi": null,
> 		……
> 		"area": {
> 			"townName": "",
> 			"cityName": "朝阳区",
> 			"success": true,
> 			"provinceName": "北京",
> 			"countyName": "三环以内"
> 		},
> 		……
> 		"StockState": 34,
> 		"StockStateName": "无货",
> 		……
> 		"ArrivalDate": "",
> 		"v": "0"
> 	},
> 	"choseSuit": []
> }
> ```
> 
> 目前我在419行的payload里添加了商品venderId（好像就是店铺首页url的那串数字），然后在stock_state之前添加了resp_json = resp_json['stock']

你好，请问方便把你修改过的文件发出来吗，我按照了你的修改会直接无法运行

**Comment by tychxn** [comment]
马上修复

**Comment by tychxn** [comment]
不好意思，问题已修复
