### ISSUE TITLE
正常运行，有几个问题恳请解答一下

### ISSUE THREAD

**Issue by ghost** [tychxn/jd-assistant#49]
无意中看到作者作品，感谢开源。代码写得很详细，赞一个。虽然我不懂PY。
1.请问eid和fp两个参数是什么意思？两个参数都用默认的有什么影响吗？默认的有效期是多久呢？
2.能否实现一下eid和fp的获得进行代码实现呢？
优化建议：
1.我测试了一个下架商品。使用的是查库存下单模式，发现在下架商品中是无法加入购物车的，所以 后面 查询到库存以后再下单我怀疑会失败。
2.在测试阶段发现 当查库存接口返回了 有货，但是仍然下单失败，经过初步排查我认为是因为店家在后台补充了库存，但是没有把商品上架，所以会一直下单失败。建议 针对已经下架的商品除了监测后台是否有库存，还要监测商品是否正常上架了。
以上的两个问题都是基于已经下架的商品做的测试，可能情况有些特殊，还请作者持续完善。
如描述不清楚的地方请和我联系企鹅：1127653664

**Comment by daiyihui** [comment]
测试

**Comment by 2010dainifei** [comment]
我是楼上的，刚才的账号注销了，重新注册了一个新的

**Comment by tychxn** [comment]
- eid 和 fp 两个参数当时简单分析过，是浏览器端 js 运行后生成的，应该是某些接口用来做标识之类的，目前看来一直使用没有什么影响。如果想要动态获取这两个参数，需要用 Python 运行 js，或用 Python 实现一遍 js 的逻辑，考虑比较麻烦所以就没有实现。
- 关于优化建议，这个确实当时没有考虑到有下架商品的情况，我晚点抓包看一下数据。

非常感谢这么详细的 issue～

**Comment by 2010dainifei** [comment]
> * eid 和 fp 两个参数当时简单分析过，是浏览器端 js 运行后生成的，应该是某些接口用来做标识之类的，目前看来一直使用没有什么影响。如果想要动态获取这两个参数，需要用 Python 运行 js，或用 Python 实现一遍 js 的逻辑，考虑比较麻烦所以就没有实现。
> * 关于优化建议，这个确实当时没有考虑到有下架商品的情况，我晚点抓包看一下数据。
> 
> 非常感谢这么详细的 issue～

曾经我用JAVA写过和你一样的东西，当时功能全部正常，唯独eid或者fp(具体哪一个记不清了)需要加密的JS动态生成，这个当时我测试会影响到抢购模式下的购买，其他没影响。我印象里eid和fp是有有效期的，过了有效期就无用了需要重新生成，这个可以持续观察一下，这是我以前测试的结果。关于后期优化建议将所有配置抽出来，单独放到配置文件中。
曾经我也有做开源软件，根据经验给您提一个意见：做开源不要听信别人想要什么你就做什么，别人想要什么功能你就加什么，这样最后软件会变得很鸡肋，很繁重，会有一堆用不上的功能。您需要做的是你自己想做什么就加什么，用户想要什么需要你做考量使用场景大不大，值不值得做，千万不要轻信别人使用量很大等等。

**Comment by tychxn** [comment]
> > * eid 和 fp 两个参数当时简单分析过，是浏览器端 js 运行后生成的，应该是某些接口用来做标识之类的，目前看来一直使用没有什么影响。如果想要动态获取这两个参数，需要用 Python 运行 js，或用 Python 实现一遍 js 的逻辑，考虑比较麻烦所以就没有实现。
> > * 关于优化建议，这个确实当时没有考虑到有下架商品的情况，我晚点抓包看一下数据。
> > 
> > 非常感谢这么详细的 issue～
> 
> 曾经我用JAVA写过和你一样的东西，当时功能全部正常，唯独eid或者fp(具体哪一个记不清了)需要加密的JS动态生成，这个当时我测试会影响到抢购模式下的购买，其他没影响。我印象里eid和fp是有有效期的，过了有效期就无用了需要重新生成，这个可以持续观察一下，这是我以前测试的结果。关于后期优化建议将所有配置抽出来，单独放到配置文件中。
> 曾经我也有做开源软件，根据经验给您提一个意见：做开源不要听信别人想要什么你就做什么，别人想要什么功能你就加什么，这样最后软件会变得很鸡肋，很繁重，会有一堆用不上的功能。您需要做的是你自己想做什么就加什么，用户想要什么需要你做考量使用场景大不大，值不值得做，千万不要轻信别人使用量很大等等。

- 当时确实分析过那段加密的 js，想着用 Python 实现一遍，函数调用栈往上追踪了好几层，最后实在没耐心推导出来。具体这两个参数对于抢购模式的影响，能力有限确实没有分析出来。
- 关于开源代码添加功能的问题，确实受教了哈哈～ 再次感谢！
