### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by Zfeiyang** [tychxn/jd-assistant#51]
1.请问python版本是否只能使用3.5.4
2.多个商品是否能一起有货下单？
3.有没有群啊，，，没用过python

**Comment by tychxn** [comment]
- Python 3.x版本都可以的
- 下单可以多商品
- 没有群，因为作者不太有空在群里解答问题😂😂😂

**Comment by Zfeiyang** [comment]
第二个问题我没有表述清楚，就是可以设置观察多个商品吗？还有您的获取商品ID的图挂了。。。麻烦您了

**Comment by EwanZhang** [comment]
多个商品查询有货下单，是否是部分有货可以部分商品提交订单？如果是所有查询商品同时提交订单，有货商品和其他没货商品一起提交，会提交订单失败。

**Comment by Zfeiyang** [comment]
> 多个商品查询有货下单，是否是部分有货可以部分商品提交订单？如果是所有查询商品同时提交订单，有货商品和其他没货商品一起提交，会提交订单失败。

...如上，添加多个商品的skuId，其中有货的并不能直接下单，口罩买不到啊。难受

**Comment by tychxn** [comment]
> 第二个问题我没有表述清楚，就是可以设置观察多个商品吗？还有您的获取商品ID的图挂了。。。麻烦您了

比如某个商品的网页url是这个 `https://item.jd.com/1178879.html`，那么商品id就是 `1178879`

**Comment by tychxn** [comment]
> > 多个商品查询有货下单，是否是部分有货可以部分商品提交订单？如果是所有查询商品同时提交订单，有货商品和其他没货商品一起提交，会提交订单失败。
> 
> ...如上，添加多个商品的skuId，其中有货的并不能直接下单，口罩买不到啊。难受

多商品监控库存，只会等到所有商品都有货之后才下单。

**Comment by EwanZhang** [comment]
提一个小建议，不知道是否容易实现，真心希望可以实现，口罩太难买了。。。
多商品现在是同时查库存，不知道能不能改成轮询。还是单商品的办法，先清空购物车，然后不要添加商品，先每个商品轮询库存，轮询到某个商品有货，就添加到购物车提交订单。

**Comment by tychxn** [comment]
> 多商品现在是同时查库存，不知道能不能改成轮询。还是单商品的办法，先清空购物车，然后不要添加商品，先每个商品轮询库存，轮询到某个商品有货，就添加到购物车提交订单。

收到，这个建议我考虑一下

**Comment by lihao010** [comment]
您好 
我在使用您的代码时
有时候在下单时会提示使用优惠券失败
无法下单 
请问这是什么状况
但是自己过一会就会恢复

**Comment by lihao010** [comment]
例如这个订单提交失败, 错误码：0, 返回信息：抱歉，您购买的商品不支持开电子发票！(下单商品可能为第三方商品，将切换为普通发票进行尝试)
[2020-01-29 07:22:56] {'overSea': False, 'orderXml': None, 'cartXml': None, 'noStockSkuIds': '', 'reqInfo': None, 'hasJxj': False, 'addedServiceList': None, 'sign': None, 'pin': 'jd_76defa5522a6e', 'needCheckCode': False, 'success': False, 'resultCode': 0, 'orderId': 0, 'submitSkuNum': 0, 'deductMoneyFlag': 0, 'goJumpOrderCenter': False, 'payInfo': None, 'scaleSkuInfoListVO': None, 'purchaseSkuInfoListVO': None, 'noSupportHomeServiceSkuList': None, 'msgMobile': None, 'addressVO': None, 'msgUuid': None, 'message': '抱歉，您购买的商品不支持开电子

**Comment by lihao010** [comment]
还有时会出现优惠券使用失败 
然后不能成功提交订单

**Comment by HJingshun** [comment]
区域ID需要更改吗？

**Comment by tychxn** [comment]
> 还有时会出现优惠券使用失败
> 然后不能成功提交订单

确实有时候会提示“优惠券使用失败”，具体原因暂时还没找到，在查。

**Comment by tychxn** [comment]
> 例如这个订单提交失败, 错误码：0, 返回信息：抱歉，您购买的商品不支持开电子发票！(下单商品可能为第三方商品，将切换为普通发票进行尝试)
> [2020-01-29 07:22:56] {'overSea': False, 'orderXml': None, 'cartXml': None, 'noStockSkuIds': '', 'reqInfo': None, 'hasJxj': False, 'addedServiceList': None, 'sign': None, 'pin': 'jd_76defa5522a6e', 'needCheckCode': False, 'success': False, 'resultCode': 0, 'orderId': 0, 'submitSkuNum': 0, 'deductMoneyFlag': 0, 'goJumpOrderCenter': False, 'payInfo': None, 'scaleSkuInfoListVO': None, 'purchaseSkuInfoListVO': None, 'noSupportHomeServiceSkuList': None, 'msgMobile': None, 'addressVO': None, 'msgUuid': None, 'message': '抱歉，您购买的商品不支持开电子

这种提示是已知的发票问题，代码会自动切换发票模式再进行下单。

**Comment by tychxn** [comment]
> 区域ID需要更改吗？

要，在`area_id`文件夹中查找自己区域的ID即可。

**Comment by tychxn** [comment]
> 提一个小建议，不知道是否容易实现，真心希望可以实现，口罩太难买了。。。
> 多商品现在是同时查库存，不知道能不能改成轮询。还是单商品的办法，先清空购物车，然后不要添加商品，先每个商品轮询库存，轮询到某个商品有货，就添加到购物车提交订单。

重写了这部分代码，现在就是采用你所说的这个逻辑，并且优化了一下不用清空购物车了

**Comment by jiam9700** [comment]
您好，我用您的代码1s监控一次库存并下单，但是查询次数多了console的提示会不动，不知道是在查询还是出了bug

**Comment by tychxn** [comment]
> 您好，我用您的代码1s监控一次库存并下单，但是查询次数多了console的提示会不动，不知道是在查询还是出了bug

可能是时间间隔太小，次数多了拿不到京东响应，一直卡住
