### ISSUE TITLE
有货提交 如何设置订单数量？

### ISSUE THREAD

**Issue by ntsafe** [tychxn/jd-assistant#52]
我看默认是1个，如何能调整

**Comment by tychxn** [comment]
```python
    def add_item_to_cart(self, sku_ids):
        """添加商品到购物车
        重要：
        1.商品添加到购物车后将会自动被勾选✓中。
        2.在提交订单时会对勾选的商品进行结算。
        3.部分商品（如预售、下架等）无法添加到购物车
        京东购物车可容纳的最大商品种数约为118-120种，超过数量会加入购物车失败。
        :param sku_ids: 商品id，格式："123" 或 "123,456" 或 "123:1,456:2" 或 {"123":1, "456":2}。若不配置数量，默认为1个。
        :return:
        """
```

添加购物车时可以用`:`  在商品id后面加上数量，比如 `123456:2`

**Comment by ntsafe** [comment]
发现一个bug
有货下单两个订单。不能同时处理。
一个有货，一个没有货的处理一个就放购物车了。
而且不能重复下单

**Comment by ntsafe** [comment]
[root@iZ8vfzmtxth7zwZ ~]# python3 kouzhao.py
2020-01-28 23:40:26,139 INFO: 登录成功
2020-01-28 23:40:26,420 INFO: 购物车清空成功
2020-01-28 23:40:26,760 INFO: [100011293950] 已上架，检测通过
2020-01-28 23:40:26,883 INFO: 100011293950 x 100 已成功加入购物车
Traceback (most recent call last):
  File "kouzhao.py", line 11, in <module>
    asst.submit_order_by_stock(sku_ids=sku_ids, area=area, interval=3)  # 监控的商品idid，库存满足时提交订单
  File "/root/jd_assistant.py", line 874, in submit_order_by_stock
    if self.if_item_can_be_ordered(sku_ids=sku_ids, area=area):
  File "/root/jd_assistant.py", line 544, in if_item_can_be_ordered
    else self.get_single_item_stock(sku_id=sku_ids[0], area=area)

**Comment by ntsafe** [comment]
from jd_assistant import Assistant

if __name__ == '__main__':
    sku_ids = '100011293950:100'  # 商品id
    area = '3_51044_25708'        # 区域id
    asst = Assistant()        # 初始化
    asst.login_by_QRcode()    # 扫码登陆
    asst.clear_cart()         # 清空购物车
    asst.check_item_state(sku_ids=sku_ids)  # 循环判断商品是否上架
    asst.add_item_to_cart(sku_ids=sku_ids)  # 将商品添加到购物车
    asst.submit_order_by_stock(sku_ids=sku_ids, area=area, interval=3)  # 监控的商品id和地址id，库存满足时提交订单
代码有问题？？

**Comment by ntsafe** [comment]
[root@iZ8vfzmtxth7zwZ ~]# python3 kouzhao.py
2020-01-28 23:43:59,086 INFO: 登录成功
2020-01-28 23:43:59,343 INFO: 购物车清空成功
2020-01-28 23:43:59,616 INFO: [100011293950] 已上架，检测通过
2020-01-28 23:43:59,743 INFO: 100011293950 x 100 已成功加入购物车
Traceback (most recent call last):
  File "kouzhao.py", line 11, in <module>
    asst.submit_order_by_stock(sku_ids=sku_ids, area=area, interval=3)  # 监控的商品idid，库存满足时提交订单
  File "/root/jd_assistant.py", line 874, in submit_order_by_stock
    if self.if_item_can_be_ordered(sku_ids=sku_ids, area=area):
  File "/root/jd_assistant.py", line 544, in if_item_can_be_ordered
    else self.get_single_item_stock(sku_id=sku_ids[0], area=area)
KeyError: 0

**Comment by tychxn** [comment]
> [root@iZ8vfzmtxth7zwZ ~]# python3 kouzhao.py
> 2020-01-28 23:43:59,086 INFO: 登录成功
> 2020-01-28 23:43:59,343 INFO: 购物车清空成功
> 2020-01-28 23:43:59,616 INFO: [100011293950] 已上架，检测通过
> 2020-01-28 23:43:59,743 INFO: 100011293950 x 100 已成功加入购物车
> Traceback (most recent call last):
> File "kouzhao.py", line 11, in
> asst.submit_order_by_stock(sku_ids=sku_ids, area=area, interval=3) # 监控的商品idid，库存满足时提交订单
> File "/root/jd_assistant.py", line 874, in submit_order_by_stock
> if self.if_item_can_be_ordered(sku_ids=sku_ids, area=area):
> File "/root/jd_assistant.py", line 544, in if_item_can_be_ordered
> else self.get_single_item_stock(sku_id=sku_ids[0], area=area)
> KeyError: 0

我查一下是不是接口参数问题

**Comment by ntsafe** [comment]
@tychxn 还是出错

**Comment by ntsafe** [comment]
@tychxn 最好是有货订单成功了，可以连续购物车下单

**Comment by ntsafe** [comment]
代码今天能更新吗。

**Comment by tychxn** [comment]
> 代码今天能更新吗。

可以，在修复bug，稍后push，建议等下用普通商品试一下软件能不能下单成功

**Comment by tychxn** [comment]
> @tychxn 能否支持连续下单。不停止任务

暂时没有支持这个功能的计划，因为下单偶尔还是会出现一些异常

**Comment by ntsafe** [comment]
@tychxn 逻辑错误，同时两个商品进行有货提交，但是又一个货下架了，另外一个货未进行直接提交，而是死循环到下架方面

**Comment by ntsafe** [comment]
@tychxn  这太不科学了啊

**Comment by ntsafe** [comment]
建议加入两个功能，
1.有货邮件货公众号提醒。
我可以支持微信公众号。这样发展的更快。
2.有货最少可购买量。比如我设置的默认有货拍100个，可是系统只能购置20个。不能错过有货。那就默认支持最少购置

**Comment by tychxn** [comment]
重写了一下有货下单功能，可以试一下
