### ISSUE TITLE
账户登录问题。12小时需要更新京东扫描登陆

### ISSUE THREAD

**Issue by ntsafe** [tychxn/jd-assistant#57]
@tychxn 有没有办法能避开这个扫描登陆，主要是我的服务器需要12小时重启一次。然后再启动进程就需要扫描登陆！

**Comment by tychxn** [comment]
这个应该是受限于京东的服务端session过期时间，可能可以通过开一个线程定时发送请求延长session的有效期，得研究一下

**Comment by ntsafe** [comment]
这个功能要更新好，不然登录很麻烦

**Comment by z1027001** [comment]
你这提问态度可以礼貌一点吗

**Comment by ntsafe** [comment]
@z1027001  我咋了啊。。。。

**Comment by tychxn** [comment]
@ntsafe 看最近有没有空吧

@z1027001 感谢～
