### ISSUE TITLE
global_config啥情况

### ISSUE THREAD

**Issue by Riser-bz** [tychxn/jd-assistant#58]
![报错](https://user-images.githubusercontent.com/58041084/73605960-eded5900-45df-11ea-9ef3-627a37ecdd3d.png)

**Comment by tychxn** [comment]
麻烦贴一下具体的报错日志信息

**Comment by Riser-bz** [comment]
> 
> 
> 麻烦贴一下具体的报错日志信息

贴了
![报错](https://user-images.githubusercontent.com/58041084/73606005-402e7a00-45e0-11ea-8951-ec8ba0a5c5e2.png)

**Comment by tychxn** [comment]
安装一下第三方库：

```shell
pip install -r requirements.txt
```

**Comment by Riser-bz** [comment]
还是这样。。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tychxn"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月2日(星期天) 下午5:24
收件人:&nbsp;"tychxn/jd-assistant"<jd-assistant@noreply.github.com&gt;;
抄送:&nbsp;"包祖鹏"<1090206380@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tychxn/jd-assistant] global_config啥情况 (#58)




安装一下第三方库：
 pip install -r requirements.txt

**Comment by Riser-bz** [comment]
> 
> 
> 安装一下第三方库：
> 
> ```shell
> pip install -r requirements.txt
> ```

![当前配置](https://user-images.githubusercontent.com/58041084/73606776-ba62fc80-45e8-11ea-940c-9a4048ab009a.png)
![error](https://user-images.githubusercontent.com/58041084/73606780-c0f17400-45e8-11ea-90ec-cbcc56fdfe88.png)
还是这样。。。

**Comment by z1027001** [comment]
你这提问语气就不能稍微可以礼貌一点吗

**Comment by Riser-bz** [comment]
抱歉抱歉，，上面没有表情包，唉😔



---原始邮件---
发件人: "z1027001"<notifications@github.com&gt;
发送时间: 2020年2月2日(周日) 晚上7:27
收件人: "tychxn/jd-assistant"<jd-assistant@noreply.github.com&gt;;
抄送: "Riser-bz"<1090206380@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [tychxn/jd-assistant] global_config啥情况 (#58)



你这提问语气就不能稍微可以礼貌一点吗

**Comment by Riser-bz** [comment]
麻烦呢您了，请问这个问题应该咋解决啊



---原始邮件---
发件人: "z1027001"<notifications@github.com&gt;
发送时间: 2020年2月2日(周日) 晚上7:27
收件人: "tychxn/jd-assistant"<jd-assistant@noreply.github.com&gt;;
抄送: "Riser-bz"<1090206380@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [tychxn/jd-assistant] global_config啥情况 (#58)



你这提问语气就不能稍微可以礼貌一点吗

**Comment by tychxn** [comment]
- 程序的主入口在 main.py，可以贴一下调用的代码
- 如果确认第三方依赖包已经安装好，感觉应该不会出现这种问题，可以在Python命令行中测试一下这几个import语句能不能执行成功
- 如果还是不行，感觉也没有什么其他方法了

**Comment by Riser-bz** [comment]
嗯嗯，谢谢您，我再去试一试



---原始邮件---
发件人: "Tychxn"<notifications@github.com&gt;
发送时间: 2020年2月2日(周日) 晚上8:54
收件人: "tychxn/jd-assistant"<jd-assistant@noreply.github.com&gt;;
抄送: "Riser-bz"<1090206380@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [tychxn/jd-assistant] global_config啥情况 (#58)


 
程序的主入口在 main.py，可以贴一下调用的代码 

如果确认第三方依赖包已经安装好，感觉应该不会出现这种问题，可以在Python命令行中测试一下这几个import语句能不能执行成功 

如果还是不行，感觉也没有什么其他方法了
