### ISSUE TITLE
sku_ids商品ID添加多了后会提示错误

### ISSUE THREAD

**Issue by zimo0825** [tychxn/jd-assistant#59]

**Comment by zimo0825** [comment]
我添加了20个商品ID进行有货下单

**Comment by tychxn** [comment]
麻烦贴一下具体的报错日志信息

**Comment by zimo0825** [comment]
稍等




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tychxn"<notifications@github.com&gt;; 
发送时间: 2020年2月2日(星期天) 下午4:05
收件人: "tychxn/jd-assistant"<jd-assistant@noreply.github.com&gt;; 
抄送: "～～"<673087044@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tychxn/jd-assistant] sku_ids商品ID添加多了后会提示错误 (#59)




麻烦贴一下具体的报错日志信息

**Comment by zimo0825** [comment]
#报错
raceback (most recent call last):
&nbsp; File "E:/学习/jd-assistant-master/jd-assistant-master/main.py", line 12, in <module&gt;
&nbsp; &nbsp; asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=0.01)
&nbsp; File "E:\学习\jd-assistant-master\jd-assistant-master\jd_assistant.py", line 1296, in buy_item_in_stock
&nbsp; &nbsp; if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area):
&nbsp; File "E:\学习\jd-assistant-master\jd-assistant-master\jd_assistant.py", line 524, in if_item_can_be_ordered
&nbsp; &nbsp; in_stock = self.get_single_item_stock(sku_id=sku_id, num=count, area=area)
&nbsp; File "E:\学习\jd-assistant-master\jd-assistant-master\jd_assistant.py", line 419, in get_single_item_stock
&nbsp; &nbsp; cat = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

#sku_id添加多了就会这样
if __name__ == '__main__':
    sku_ids = '100006784140,11609510701,65402985519,65399049577,34197525576,34197525576,1238056920,41157965868,41157965869,41157965870,41157965871' \
              '20111976846,65425149164,10653857950,10653857951,1938795,100005666820,1835968,1835967,1938788,1891756,100010439846,100009450890'  # 商品id
    # 代尔塔 104019,1612617212;蕉下,100009130434;星工,100010159728;宜舒,62408717970;芯硅谷,100009442472;
    area = '22_2016_2020_7902'  # 区域id
    asst = Assistant()  # 初始化
    asst.login_by_QRcode()  # 扫码登陆
    asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=0.01)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tychxn"<notifications@github.com&gt;; 
发送时间: 2020年2月2日(星期天) 下午4:05
收件人: "tychxn/jd-assistant"<jd-assistant@noreply.github.com&gt;; 
抄送: "～～"<673087044@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tychxn/jd-assistant] sku_ids商品ID添加多了后会提示错误 (#59)




麻烦贴一下具体的报错日志信息

**Comment by tychxn** [comment]
我得试一下  
看起来是某个商品的页面信息比较特殊，无法获取到信息

**Comment by tychxn** [comment]
商品id换行的时候写错了，第一行末尾没有加上`,`导致有个商品id是错误的

```diff
if __name__ == '__main__':
-    sku_ids = '100006784140,11609510701,65402985519,65399049577,34197525576,34197525576,1238056920,41157965868,41157965869,41157965870,41157965871' \
+    sku_ids = '100006784140,11609510701,65402985519,65399049577,34197525576,34197525576,1238056920,41157965868,41157965869,41157965870,41157965871,' \
              '20111976846,65425149164,10653857950,10653857951,1938795,100005666820,1835968,1835967,1938788,1891756,100010439846,100009450890'  # 商品id

```

**Comment by zimo0825** [comment]
哈哈哈，没注意到




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tychxn"<notifications@github.com&gt;; 
发送时间: 2020年2月2日(星期天) 下午4:34
收件人: "tychxn/jd-assistant"<jd-assistant@noreply.github.com&gt;; 
抄送: "～～"<673087044@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tychxn/jd-assistant] sku_ids商品ID添加多了后会提示错误 (#59)




商品id换行的时候写错了，第一行末尾没有加上,导致有个商品id是错误的
 if __name__ == '__main__': -    sku_ids = '100006784140,11609510701,65402985519,65399049577,34197525576,34197525576,1238056920,41157965868,41157965869,41157965870,41157965871' \ +    sku_ids = '100006784140,11609510701,65402985519,65399049577,34197525576,34197525576,1238056920,41157965868,41157965869,41157965870,41157965871,' \               '20111976846,65425149164,10653857950,10653857951,1938795,100005666820,1835968,1835967,1938788,1891756,100010439846,100009450890'  # 商品id

**Comment by tychxn** [comment]
😂 closed.
