### ISSUE TITLE
有货下单报错 AttributeError: 'Assistant' object has no attribute 'buy_item_in_stock'

### ISSUE THREAD

**Issue by zdghit** [tychxn/jd-assistant#60]
from jd_assistant import Assistant

if __name__ == '__main__':
    """
    重要提示：此处为示例代码之一，请移步下面的链接查看使用教程👇
    https://github.com/tychxn/jd-assistant/wiki/1.-%E4%BA%AC%E4%B8%9C%E6%8A%A2%E8%B4%AD%E5%8A%A9%E6%89%8B%E7%94%A8%E6%B3%95
    """

    sku_ids = '100010159778:4'  # 商品id
    area = '1_2800_4209'        # 区域id
    asst = Assistant()        # 初始化
    asst.login_by_QRcode()    # 扫码登陆
    asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=5)

**Comment by tychxn** [comment]
感觉是代码没有更新，pull一下最新代码试试看

**Comment by zdghit** [comment]
是最新的代码 不能复现吗

**Comment by tychxn** [comment]
额 最新的代码不会找不到这个方法调用啊

**Comment by zdghit** [comment]
知道了 我下载的是码云的代码 这个不是最新的啊。。重下github就好了
https://gitee.com/tychxn/jd-assistant

**Comment by tychxn** [comment]
尴尬，可能是码云没有同步，不好意思
