### ISSUE TITLE
运行更新的代码报 'stock'  key错误

### ISSUE THREAD

**Issue by Aking-TT** [tychxn/jd-assistant#61]
发生异常: KeyError
'stock'
  File "D:\Python37\jd-assistant-master_1.0\jd_assistant.py", line 444, in get_single_item_stock
    stock_state = resp_json['stock']['StockState']  # 33 -- 现货  0,34 -- 无货  36 -- '采购中'  40 -- 可配货
  File "D:\Python37\jd-assistant-master_1.0\jd_assistant.py", line 524, in if_item_can_be_ordered
    in_stock = self.get_single_item_stock(sku_id=sku_id, num=count, area=area)
  File "D:\Python37\jd-assistant-master_1.0\jd_assistant.py", line 1296, in buy_item_in_stock
    if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area):
  File "D:\Python37\jd-assistant-master_1.0\main.py", line 18, in <module>
    asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=5)

**Comment by tychxn** [comment]
使用代码贴一下，我看看是不是商品id有问题

**Comment by Aking-TT** [comment]
from jd_assistant import Assistant

if __name__ == '__main__':
    """
    重要提示：此处为示例代码之一，请移步下面的链接查看使用教程👇
    https://github.com/tychxn/jd-assistant/wiki/1.-%E4%BA%AC%E4%B8%9C%E6%8A%A2%E8%B4%AD%E5%8A%A9%E6%89%8B%E7%94%A8%E6%B3%95
    """
    sku_ids = '100011295518,100011293952,100006248177:2'
    area = '12-904-3378-57891'
    asst = Assistant()  # 初始化
    asst.login_by_QRcode()  # 扫码登陆
    asst.clear_cart()
    # asst.check_item_state(sku_ids=sku_ids)
    # asst.add_item_to_cart(sku_ids=sku_ids)
    #asst.submit_order_by_stock(sku_ids=sku_ids, area=area, interval=2)
    asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=5)

**Comment by Aking-TT** [comment]
这三个id，使用原来旧的代码没有问题，Falsewait_all=False,设成True，也不会报错

**Comment by tychxn** [comment]
地址id改为下划线`_`进行分割，下个版本我兼容一下

```python
area = '12_904_3378_57891'
```

**Comment by tychxn** [comment]
closed.
