### ISSUE TITLE
请问下这是什么问题

### ISSUE THREAD

**Issue by 448455654** [tychxn/jd-assistant#62]
![QQ图片20200202203358](https://user-images.githubusercontent.com/30015771/73608230-7b8a7200-45fb-11ea-93d0-3bf6dc1d3053.png)

**Comment by tychxn** [comment]
应该是商品id错误，再确认一下，或者贴出来看看

**Comment by tychxn** [comment]
也有可能是地址id写错了，可以参考这个issue https://github.com/tychxn/jd-assistant/issues/61

**Comment by 448455654** [comment]
from jd_assistant import Assistant

if __name__ == '__main__':
    sku_ids = '100011293950,100006248177,100006248247,100011293928,1336984'  # 商品id
    area = '12_988_994_48128'        # 区域id
    asst = Assistant()        # 初始化
    asst.login_by_QRcode()    # 扫码登陆
    asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=0.2)

**Comment by tychxn** [comment]
![image](https://user-images.githubusercontent.com/29301320/73624476-e2e80680-467b-11ea-9600-fbff6df48357.png)
我这里测试没有问题

**Comment by midle110** [comment]
不是第一次出现的
是跑了一段时间之后出现的

我更新最新版版本看看还会不会出现

**Comment by tychxn** [comment]
> 不是第一次出现的
> 是跑了一段时间之后出现的
> 
> 我更新最新版版本看看还会不会出现

查询库存的间隔不要太小了
