### ISSUE TITLE
跑一段时间后卡住？

### ISSUE THREAD

**Issue by htt1994** [tychxn/jd-assistant#63]
代码成功运行，但是运行一段时间后会卡住或者出现一些奇怪的错误（还不一样），这是因为查询过于频繁吗？如果是，一般查询时间还有提交订单时间间隔是多少？按照默认？

**Comment by tychxn** [comment]
- 有可能是因为间隔太短了，建议长一些
- 刚刚改了下代码，加了查询库存请求超时，应该能好一些

**Comment by maidamai0** [comment]
@htt1994 
我昨天遇到类似的情况，后来发现是我本地网络不好的原因，你可以把提交的那段代码放到try/exception里面，抓到异常之后继续跑就行了。
你也可以把详细的错误信息复制过来我们看下。

**Comment by liwenza** [comment]
如何一次添加多个sku ID？

**Comment by htt1994** [comment]
> * 有可能是因为间隔太短了，建议长一些
> * 刚刚改了下代码，加了查询库存请求超时，应该能好一些

ok，非常感谢！

**Comment by htt1994** [comment]
> @htt1994
> 我昨天遇到类似的情况，后来发现是我本地网络不好的原因，你可以把提交的那段代码放到try/exception里面，抓到异常之后继续跑就行了。
> 你也可以把详细的错误信息复制过来我们看下。

好主意，我试试

**Comment by maidamai0** [comment]
> 如何一次添加多个sku ID？

1. 你的问题和这个issue没有关系，建议新开一个issue。
2. 在util.py文件里面， parse_sku_id函数中可以看到注释:
```
    """将商品id字符串解析为字典

    商品id字符串采用英文逗号进行分割。
    可以在每个id后面用冒号加上数字，代表该商品的数量，如果不加数量则默认为1。

    例如：
    输入  -->  解析结果
    '123456' --> {'123456': '1'}
    '123456,123789' --> {'123456': '1', '123789': '1'}
    '123456:1,123789:3' --> {'123456': '1', '123789': '3'}
    '123456:2,123789' --> {'123456': '2', '123789': '1'}

    :param sku_ids: 商品id字符串
    :return: dict
    """
```
