### ISSUE TITLE
统一回复：看情况更新代码，不再回复邮件了

### ISSUE THREAD

**Issue by tychxn** [tychxn/jd-assistant#64]
最近邮件咨询实在太多了，考虑到个人时间有限，这里统一回复下：

- ~~短期内不会~~看情况更新代码
- 不再回复邮件
- 没有，未来也不会创建任何形式的讨论群
- 引用 / 复制代码如果能添加源 repo 地址就更好了

**Comment by Oppswhite** [comment]
感谢作者，成功帮助抢到了足够个人使用的口罩，另外可以考虑增加赞助方式

**Comment by Davon11** [comment]
劳烦问一下，3.1.3 有货提交订单示例中参数：地区id  是什么？

**Comment by maidamai0** [comment]
> 感谢作者，成功帮助抢到了足够个人使用的口罩，另外可以考虑增加赞助方式

现在还能抢到口罩吗？我听说现在口罩企业都被征用了，我看jd上的口罩也一直断货，很多已经下单的也被店家要求退款。有推荐的吗，万分感谢，现在没有口罩不让出门了。

**Comment by zl1013** [comment]
有货下单逻辑想修改为不添加购物车直接下单，大佬可以做指点下吗？

**Comment by tychxn** [comment]
> 有货下单逻辑想修改为不添加购物车直接下单，大佬可以做指点下吗？

参考wiki中`直接提交订单示例`，以及`buy_item_in_stock`这个方法的实现。

**Comment by Yolk24** [comment]
我是macOS系统，为什么想安装第三方库的时候会出现SyntaxError: invalid syntax这个错误，有哪位大神解答一下吗，谢谢

**Comment by yyingc** [comment]
Windows下一键安装python和第三方库，方便立刻使用jd-assistant脚本。
先到官网 下载：https://www.python.org/ftp/python/3.8.1/python-3.8.1-amd64.exe
将下面代码保存为 pythoninstall.bat 放在和python-3.8.1-amd64.exe同一文件夹，然后执行pythoninstall.bat 进行安装。
之后你就可以使用tychxn作者的jd-assistant脚本了，修改main.py然后，点击运行即可。
`@ECHO OFF
>NUL 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"
IF '%errorlevel%' NEQ '0' (
GOTO UACPrompt
) ELSE ( GOTO gotAdmin )
:UACPrompt
ECHO Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
ECHO UAC.ShellExecute "%~s0", "", "", "runas", 1 >> "%temp%\getadmin.vbs"
"%temp%\getadmin.vbs"
EXIT /B
:gotAdmin
IF EXIST "%temp%\getadmin.vbs" ( DEL "%temp%\getadmin.vbs" )
title 一键安装python
color 2F
pushd "%~dp0"
for /f "delims=" %%i in ('dir /b %~dp0\^|findstr "python-.*\.exe"') do (set python=%%i)
ECHO 正在安装%python%到%SystemDrive%\python路径……
%python% /quiet InstallAllUsers=1 TargetDir=%SystemDrive%\python PrependPath=1 Include_doc=0 Include_dev=0 Include_tcltk=0 Include_test=0
ECHO.
ECHO 更新 pip：
ping -n 5 0 >NUL
python -m pip install --upgrade pip
ECHO.
ECHO 更新工具包：
pip install --upgrade setuptools
ECHO.
ECHO 安装脚本第三方依赖库：
pip install bs4 beautifulsoup4 requests pycryptodome
ECHO.
ECHO pip 已安装模块：
pip list
ECHO.
ECHO 全部安装完毕！
ECHO.
ECHO 按任意键退出……
PAUSE>NUL
EXIT `

**Comment by jerryhuangn** [comment]
> 我是macOS系统，为什么想安装第三方库的时候会出现SyntaxError: invalid syntax这个错误，有哪位大神解答一下吗，谢谢

好像“requirements.txt”这个文件需要UTF-8编码才能正常读取。你看一下是不是这个问题。

**Comment by hui-shao** [comment]
感谢大佬，自己的只写到了监控库存，今晚拿您的试试能不能抢到口罩

**Comment by zl1013** [comment]
> > 有货下单逻辑想修改为不添加购物车直接下单，大佬可以做指点下吗？
> 
> 参考wiki中`直接提交订单示例`，以及`buy_item_in_stock`这个方法的实现。

改了半天  没改成  哈哈

**Comment by icelasa** [comment]
老大，昨天的新代码出现如下问题，怎么出破，谢谢！
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from jd_assistant import Assistant
  File "C:\Users\xxx\Desktop\jd-assistant-master\jd_assistant.py", line 18, in <module>
    from util import (
  File "C:\Users\xxx\Desktop\jd-assistant-master\util.py", line 13, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'

**Comment by icelasa** [comment]
> > > 有货下单逻辑想修改为不添加购物车直接下单，大佬可以做指点下吗？
> > 
> > 
> > 参考wiki中`直接提交订单示例`，以及`buy_item_in_stock`这个方法的实现。
> 
> 改了半天 没改成 哈哈

搞定没

**Comment by 1286320807** [comment]
每次查询间隔多少时间抢到的成功率比较高呀？

**Comment by tychxn** [comment]
> > > > 有货下单逻辑想修改为不添加购物车直接下单，大佬可以做指点下吗？
> > > 
> > > 
> > > 参考wiki中`直接提交订单示例`，以及`buy_item_in_stock`这个方法的实现。
> > 
> > 
> > 改了半天 没改成 哈哈
> 
> 搞定没

最简单的方式就是参考这个 https://github.com/tychxn/jd-assistant/issues/76 中的做法：直接注释`buy_item_in_stock`方法中的购物车操作，然后提前将商品加入购物车并勾选☑️，缺点是每次只能监控一种商品。 
@icelasa @zl1013

**Comment by zl1013** [comment]
> 
> 
> > > > > 有货下单逻辑想修改为不添加购物车直接下单，大佬可以做指点下吗？
> > > > 
> > > > 
> > > > 参考wiki中`直接提交订单示例`，以及`buy_item_in_stock`这个方法的实现。
> > > 
> > > 
> > > 改了半天 没改成 哈哈
> > 
> > 
> > 搞定没
> 
> 最简单的方式就是参考这个 #76 中的做法：直接注释`buy_item_in_stock`方法中的购物车操作，然后提前将商品加入购物车并勾选☑️，缺点是每次只能监控一种商品。
> @icelasa @zl1013

我现在更改的，还是加购，只不过不获取订单界面，直接提交订单

**Comment by icelasa** [comment]
> > > > > > 有货下单逻辑想修改为不添加购物车直接下单，大佬可以做指点下吗？
> > > > > 
> > > > > 
> > > > > 参考wiki中`直接提交订单示例`，以及`buy_item_in_stock`这个方法的实现。
> > > > 
> > > > 
> > > > 改了半天 没改成 哈哈
> > > 
> > > 
> > > 搞定没
> > 
> > 
> > 最简单的方式就是参考这个 #76 中的做法：直接注释`buy_item_in_stock`方法中的购物车操作，然后提前将商品加入购物车并勾选☑️，缺点是每次只能监控一种商品。
> > @icelasa @zl1013
> 
> 我现在更改的，还是加购，只不过不获取订单界面，直接提交订单

抢到了没？
改哪些地方？python小白。
谢谢。

**Comment by zs-liu** [comment]
> > > > > > > 有货下单逻辑想修改为不添加购物车直接下单，大佬可以做指点下吗？
> > > > > > 
> > > > > > 
> > > > > > 参考wiki中`直接提交订单示例`，以及`buy_item_in_stock`这个方法的实现。
> > > > > 
> > > > > 
> > > > > 改了半天 没改成 哈哈
> > > > 
> > > > 
> > > > 搞定没
> > > 
> > > 
> > > 最简单的方式就是参考这个 #76 中的做法：直接注释`buy_item_in_stock`方法中的购物车操作，然后提前将商品加入购物车并勾选☑️，缺点是每次只能监控一种商品。
> > > @icelasa @zl1013
> > 
> > 
> > 我现在更改的，还是加购，只不过不获取订单界面，直接提交订单
> 
> 抢到了没？
> 改哪些地方？python小白。
> 谢谢。

我理解是注释下面的（但我觉得抢到的可能性不大o(╥﹏╥)o
```python
# self._cancel_select_all_cart_item()
# self._add_or_change_cart_item(self.get_cart_detail(), sku_id, count)
```

**Comment by icelasa** [comment]
> > > > > > > > 有货下单逻辑想修改为不添加购物车直接下单，大佬可以做指点下吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 参考wiki中`直接提交订单示例`，以及`buy_item_in_stock`这个方法的实现。
> > > > > > 
> > > > > > 
> > > > > > 改了半天 没改成 哈哈
> > > > > 
> > > > > 
> > > > > 搞定没
> > > > 
> > > > 
> > > > 最简单的方式就是参考这个 #76 中的做法：直接注释`buy_item_in_stock`方法中的购物车操作，然后提前将商品加入购物车并勾选☑️，缺点是每次只能监控一种商品。
> > > > @icelasa @zl1013
> > > 
> > > 
> > > 我现在更改的，还是加购，只不过不获取订单界面，直接提交订单
> > 
> > 
> > 抢到了没？
> > 改哪些地方？python小白。
> > 谢谢。
> 
> 我理解是注释下面的（但我觉得抢到的可能性不大o(╥﹏╥)o
> 
> ```python
> # self._cancel_select_all_cart_item()
> # self._add_or_change_cart_item(self.get_cart_detail(), sku_id, count)
> ```

好的，我试试，谢谢。

**Comment by w591213060** [comment]
> Windows下一键安装python和第三方库，方便立刻使用jd-assistant脚本。
> 先到官网 下载：https://www.python.org/ftp/python/3.8.1/python-3.8.1-amd64.exe
> 将下面代码保存为 pythoninstall.bat 放在和python-3.8.1-amd64.exe同一文件夹，然后执行pythoninstall.bat 进行安装。
> 之后你就可以使用tychxn作者的jd-assistant脚本了，修改main.py然后，点击运行即可。
> 
> ```
> @ECHO OFF
> >NUL 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"
> IF '%errorlevel%' NEQ '0' (
> GOTO UACPrompt
> ) ELSE ( GOTO gotAdmin )
> :UACPrompt
> ECHO Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
> ECHO UAC.ShellExecute "%~s0", "", "", "runas", 1 >> "%temp%\getadmin.vbs"
> "%temp%\getadmin.vbs"
> EXIT /B
> :gotAdmin
> IF EXIST "%temp%\getadmin.vbs" ( DEL "%temp%\getadmin.vbs" )
> title 一键安装python
> color 2F
> pushd "%~dp0"
> for /f "delims=" %%i in ('dir /b %~dp0\^|findstr "python-.*\.exe"') do (set python=%%i)
> ECHO 正在安装%python%到%SystemDrive%\python路径……
> %python% /quiet InstallAllUsers=1 TargetDir=%SystemDrive%\python PrependPath=1 Include_doc=0 Include_dev=0 Include_tcltk=0 Include_test=0
> ECHO.
> ECHO 更新 pip：
> ping -n 5 0 >NUL
> python -m pip install --upgrade pip
> ECHO.
> ECHO 更新工具包：
> pip install --upgrade setuptools
> ECHO.
> ECHO 安装脚本第三方依赖库：
> pip install bs4 beautifulsoup4 requests pycryptodome
> ECHO.
> ECHO pip 已安装模块：
> pip list
> ECHO.
> ECHO 全部安装完毕！
> ECHO.
> ECHO 按任意键退出……
> PAUSE>NUL
> EXIT
> ```
怎么生成这个BAT呢?大神
