### ISSUE TITLE
监控有货，下单无货

### ISSUE THREAD

**Issue by accfcx** [tychxn/jd-assistant#76]
14:55:36,314 INFO: 1835967 满足下单条件，开始执行
2020-02-07 14:55:36,655 INFO: 购物车信息：{}
2020-02-07 14:55:36,655 INFO: 1835967 不在购物车中，开始加入购物车，数量 1
2020-02-07 14:55:36,889 INFO: 1835967 x 1 已成功加入购物车
2020-02-07 14:55:36,890 INFO: 第[1/5]次尝试提交订单
2020-02-07 14:55:37,534 INFO: 下单信息：XXX
2020-02-07 14:55:37,631 INFO: 订单提交失败, 错误码：600158, 返回信息：3M 带阀防护口罩 KN95折叠耳带式防雾霾防沙尘 9501V 25只/盒 独立包装（新老包装随机发放）商品无货

监控了一个3m口罩，重试后面的参数都不重要，主要是从监控有货到最终下单之间的耗时太长，导致一直失败。

**Comment by zaiweijian** [comment]
因为一大半人都在抢

**Comment by accfcx** [comment]
> 因为一大半人都在抢



> 因为一大半人都在抢

抢口罩和其它比如书全程都是耗时至少1s，咱也不知道怎么优化这一点；希望针对这一点能给优化一下，不然天天都是陪跑

**Comment by zaiweijian** [comment]
> > 因为一大半人都在抢
> 
> > 因为一大半人都在抢
> 
> 抢口罩和其它比如书全程都是耗时至少1s，咱也不知道怎么优化这一点；希望针对这一点能给优化一下，不然天天都是陪跑

想什么呢，京东一次就上几件，全国都在盯着。人家都是租低延时服务器，咱们要想抢到只能靠狗东多上几个库存了

**Comment by tychxn** [comment]
为了能做一个通用的方案，所以效率慢了一些（其实也就多了查询购物车+将商品加入购物车这两步），master分支上目前不会考虑优化。

有能力可以自己改造，先将商品加入购物车并勾选好，然后监控库存，有货直接下单而不是让程序来加入购物车再下单。

**Comment by accfcx** [comment]
> 为了能做一个通用的方案，所以效率慢了一些（其实也就多了查询购物车+将商品加入购物车这两步），master分支上目前不会考虑优化。
> 
> 有能力可以自己改造，先将商品加入购物车并勾选好，然后监控库存，有货直接下单而不是让程序来加入购物车再下单。

之前只是简单改了监控时间和重试相关参数，今天看了时间相关，才发现是步骤耗时的原因；正在修改去掉无关步骤，还没有能力做进一步优化

**Comment by tychxn** [comment]
> > 为了能做一个通用的方案，所以效率慢了一些（其实也就多了查询购物车+将商品加入购物车这两步），master分支上目前不会考虑优化。
> > 有能力可以自己改造，先将商品加入购物车并勾选好，然后监控库存，有货直接下单而不是让程序来加入购物车再下单。
> 
> 之前只是简单改了监控时间和重试相关参数，今天看了时间相关，才发现是步骤耗时的原因；正在修改去掉无关步骤，还没有能力做进一步优化

想要优化步骤就按照上面说的去做好了，主代码不考虑优化了。

**Comment by zaiweijian** [comment]
> > > 为了能做一个通用的方案，所以效率慢了一些（其实也就多了查询购物车+将商品加入购物车这两步），master分支上目前不会考虑优化。
> > > 有能力可以自己改造，先将商品加入购物车并勾选好，然后监控库存，有货直接下单而不是让程序来加入购物车再下单。
> > 
> > 
> > 之前只是简单改了监控时间和重试相关参数，今天看了时间相关，才发现是步骤耗时的原因；正在修改去掉无关步骤，还没有能力做进一步优化
> 
> 想要优化步骤就按照上面说的去做好了，主代码不考虑优化了。


> > > 为了能做一个通用的方案，所以效率慢了一些（其实也就多了查询购物车+将商品加入购物车这两步），master分支上目前不会考虑优化。
> > > 有能力可以自己改造，先将商品加入购物车并勾选好，然后监控库存，有货直接下单而不是让程序来加入购物车再下单。
> > 
> > 
> > 之前只是简单改了监控时间和重试相关参数，今天看了时间相关，才发现是步骤耗时的原因；正在修改去掉无关步骤，还没有能力做进一步优化
> 
> 想要优化步骤就按照上面说的去做好了，主代码不考虑优化了。

直接把buy_item_in_stock函数里的购物车操作给注释了。。

**Comment by tychxn** [comment]
OK, issue closed.

**Comment by jy024929** [comment]
> OK, issue closed.

注释了我发现还是要多一步下单信息，能不能改成先下单查存货信息，查到了直接提交？
