### ISSUE TITLE
预约商品 暂时有什么好的解决方案么？

### ISSUE THREAD

**Issue by littp** [tychxn/jd-assistant#8]

**Comment by tychxn** [comment]
请问指的是预约商品哪些问题的解决方案？
- 如果是执行预约流程 [刚刚添加了预约功能](https://github.com/tychxn/jd-assistant/commit/ead8c88e41e55e2a41ad970ba92be9506e7313bb)
- 京东限制预约商品无法加入购物车

**Comment by littp** [comment]
我是指的预约商品的自动抢购功能，已经预约的商品，不可以直接加入购物车，但是可以直接购买。

**Comment by tychxn** [comment]
你指的是类似这样的购买方式是吧 [https://item.jd.com/100000177756.html](https://item.jd.com/100000177756.html)
之前我没有遇到过，要不帮忙抓个包看看

**Comment by littp** [comment]
https://item.jd.com/251837.html 是这样的
1、先预约抢购时间 ，2、到时间之后，直接点击抢购按钮，就跳转到了下单页面
我还没找到相同的产品是这种形式的，这个已经无货 没办法测试了

**Comment by tychxn** [comment]
能不能下次抢购抓一下数据包  发我看一下 ;)

**Comment by littp** [comment]
好 ，我试试。
但是怎么抓。。。都要哪些元素。我没抓过 -。- 
手机和PC都行么？

**Comment by tychxn** [comment]
你看以下这个网页 https://item.jd.com/100000177756.html  是不是流程有点类似
- windows上抓包可以用Fiddler
- mac上可以使用Charles

Google一下教程就好了

**Comment by littp** [comment]
这个是预售不太一样，我去研究研究，回头抓下来。

**Comment by littp** [comment]
找到了 和这个差不多 https://item.jd.com/100000701050.html

**Comment by tychxn** [comment]
OK  有空我会去抓一下数据包看看
建议你也尝试抢购下单  用Fiddler把整体的数据包保存一下
