### ISSUE TITLE
cookies的时间是24小时吗？

### ISSUE THREAD

**Issue by PHCSJC** [tychxn/jd-assistant#80]
好像24小时后重新执行就会提示要扫描二维码，是cookies过期了吗？cookies的时间是24小时吗？

**Comment by tychxn** [comment]
这样提示确实是cookie过期了，大概是一天的有效期，目前还没有开发好维持cookie在线的功能

**Comment by PHCSJC** [comment]
@tychxn 直接添加用户名和密码也可以啊，反正你这个是开源的。

**Comment by tychxn** [comment]
> @tychxn 每天重新登录一次太频繁了，建议可以直接添加用户名和密码（相信开源），同时保留二维码登录。

曾经做了账号密码登录，但是京东更新后滑动验证码处理起来比较麻烦，就没有折腾
