### ISSUE TITLE
> 我也出现了这个问题，只有口罩会有这个问题，其他的，我用的你zip包里面自带的main运行的时候，就能成功下单。

### ISSUE THREAD

**Issue by xuxu7471** [tychxn/jd-assistant#87]
不知道别人怎么解决的，手动下单还是慢，不知道jd plus会员是不是没有这个情况，我现在届不到账号试，如果你有资源的话，可以借个看看能不能行。

**Comment by tychxn** [comment]
那么到底是什么问题。。。

**Comment by xuxu7471** [comment]
就是前面有个提到的，提交订单需要验证码，我在网页上试了试，确实是需要，用别人的账号试了试，也是需要验证码。特别是买口罩需要，买别的没发现，可能京东新增的功能，防止脚本？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tychxn <notifications@github.com&gt;
发送时间: 2020年2月9日 13:19
收件人: tychxn/jd-assistant <jd-assistant@noreply.github.com&gt;
抄送: xuxu7471 <782770487@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tychxn/jd-assistant] &gt; 我也出现了这个问题，只有口罩会有这个问题，其他的，我用的你zip包里面自带的main运行的时候，就能成功下单。 (#87)

**Comment by tychxn** [comment]
确实有可能京东为口罩之类的重要商品增加了防护
但是更可能的原因是刷的太多太频繁，导致被风控系统识别了ip等因素

**Comment by xuxu7471** [comment]
这个换代理会不会好点？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tychxn <notifications@github.com&gt;
发送时间: 2020年2月9日 13:46
收件人: tychxn/jd-assistant <jd-assistant@noreply.github.com&gt;
抄送: xuxu7471 <782770487@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tychxn/jd-assistant] &gt; 我也出现了这个问题，只有口罩会有这个问题，其他的，我用的你zip包里面自带的main运行的时候，就能成功下单。 (#87)

**Comment by tychxn** [comment]
刚刚用自己的账户试了一下口罩商品，还没有提示验证码，你的应该是被风控识别了

换ip，换账号吧

**Comment by xuxu7471** [comment]
风控这东西多久能取消了啊，大佬有木有经验。。。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tychxn <notifications@github.com&gt;
发送时间: 2020年2月9日 13:51
收件人: tychxn/jd-assistant <jd-assistant@noreply.github.com&gt;
抄送: xuxu7471 <782770487@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tychxn/jd-assistant] &gt; 我也出现了这个问题，只有口罩会有这个问题，其他的，我用的你zip包里面自带的main运行的时候，就能成功下单。 (#87)

**Comment by pyeter-star** [comment]
口罩大都没货了吧

**Comment by For515** [comment]
大佬，验证码的问题，帮忙测一下65466451629，每天晚上11点上货可能前后差20秒，每天因为验证码卡住，您帮测一下看看今天你那边会不会也提示验证码，为此我和京东客服吼叫了半天。。。。

**Comment by dnovelty** [comment]
> 刚刚用自己的账户试了一下口罩商品，还没有提示验证码，你的应该是被风控识别了
> 
> 换ip，换账号吧
&emsp;&emsp;就是下单太多导致的。

**Comment by dnovelty** [comment]
> 刚刚用自己的账户试了一下口罩商品，还没有提示验证码，你的应该是被风控识别了
> 
> 换ip，换账号吧

&emsp;&emsp个人感觉就是下单过于频繁导致的。
