### ISSUE TITLE
第一次用github，成功后放音乐感觉不影响效率但可以起到提示，供大佬参考

### ISSUE THREAD

**Issue by mruray** [tychxn/jd-assistant#88]
我尝试了一下，在def submit_order_with_retry(self, retry=3, interval=4)这里
 if self.submit_order():
                logger.info('第%s次提交订单成功', i)
这后面加四句，当然最前面加一下import pygame
file=r'C:\Users\admin\Desktop\mask\jd-assistant-master\success.mp3'
pygame.mixer.init()
track = pygame.mixer.music.load(file)
pygame.mixer.music.play()

**Comment by tychxn** [comment]
😂在个人电脑上播放声音确实也是个通知方式

**Comment by tychxn** [comment]
thanks.
