### ISSUE TITLE
感觉判断库存的时候，会不会出现判断失误的情况？

### ISSUE THREAD

**Issue by zaiweijian** [tychxn/jd-assistant#89]
找了另一个项目的查询库存订单，一直显示没货。。。这一个就时不时显示有货，但是下单失败。

2020-02-09 09:26:16,982 INFO: 100002690366 不满足下单条件，0.01s后进行下一次查询
2020-02-09 09:26:17,062 INFO: 100002690366 不满足下单条件，0.01s后进行下一次查询
2020-02-09 09:26:17,191 INFO: 100002690366 满足下单条件，开始执行
2020-02-09 09:26:17,312 INFO: 订单提交失败, 错误码：600158, 返回信息：3M 口罩KN95 耳戴折叠式9501VT 带阀颗粒物防护口罩 独立包装 25只/盒商品无货

出现好几次这种情况，这种零点几秒就没货了。

**Comment by zaiweijian** [comment]
我现在用的，是直接事先添加购物车，然后有货时直接提交订单

**Comment by tychxn** [comment]
会的，京东库存接口刷多了有时候返回的数据不太准确。

**Comment by tychxn** [comment]
大概知道是哪个项目🤷‍♂️。

京东有两个查询库存的接口，分别对应查询单商品和多商品库存，个人一直觉得第二个接口数据可能不太准确，没有用的很多。

**Comment by 1286320807** [comment]
我拿普通商品试了一下，用一些坚果商品试，有货但是不满足下单条件，换了个华为充电宝试了又可以下单，这是为什么

**Comment by tychxn** [comment]
> 我拿普通商品试了一下，用一些坚果商品试，有货但是不满足下单条件，换了个华为充电宝试了又可以下单，这是为什么

应该是地区性没货 打开商品页面看一下本地区到底有没有货

**Comment by 1286320807** [comment]
> 
> 
> > 我拿普通商品试了一下，用一些坚果商品试，有货但是不满足下单条件，换了个华为充电宝试了又可以下单，这是为什么
> 
> 应该是地区性没货 打开商品页面看一下本地区到底有没有货

手机上下单是可以成功，python上面显示不满足下单条件。有些可以有些不可以。

**Comment by l315105l** [comment]
> 找了另一个项目的查询库存订单，一直显示没货。。。这一个时时不时显示有货，但是下单失败。
> 
> 2020-02-09 09：26：16,982 INFO：100002690366不满足下单条件，0.01s后进行下一次查询
> 2020-02-09 09：26：17,062 INFO：100002690366不满足下单条件，0.01s后进行下一次查询一次查询
> 2020-02-09 09：26：17,191信息：100002690366满足下单条件，开始执行
> 2020-02-09 09：26：17,312信息：订单提交失败，错误代码：600158，返回信息：3M口罩KN95耳戴折叠式9501VT带阀颗粒物防护口罩独立包装25只/盒商品无货
> 
> 出现好一次这种情况，这种零点几秒就没货了。

请问 如何跳过 购物车显示信息:     直接提交订单  , 就像你这样满足条件 直接下单

**Comment by mruray** [comment]
> > 找了另一个项目的查询库存订单，一直显示没货。。。这一个时时不时显示有货，但是下单失败。
> > 2020-02-09 09：26：16,982 INFO：100002690366不满足下单条件，0.01s后进行下一次查询
> > 2020-02-09 09：26：17,062 INFO：100002690366不满足下单条件，0.01s后进行下一次查询一次查询
> > 2020-02-09 09：26：17,191信息：100002690366满足下单条件，开始执行
> > 2020-02-09 09：26：17,312信息：订单提交失败，错误代码：600158，返回信息：3M口罩KN95耳戴折叠式9501VT带阀颗粒物防护口罩独立包装25只/盒商品无货
> > 出现好一次这种情况，这种零点几秒就没货了。
> 
> 请问 如何跳过 购物车显示信息: 直接提交订单 , 就像你这样满足条件 直接下单

根据作者的代码，我写了一个供参考，不会用github，我黏贴在这里。
def buy_item_in_cart(self,sku_ids,area,stock_interval=3, submit_retry=3, submit_interval=0.001):
        """为提高效率，心仪商品全部提前加入购物车，检测库存有货立马购物车中开始提交
        :param sku_ids: 商品id。可以设置多个商品，也可以带数量，如：'1234' 或 '1234,5678' 或 '1234:2' 或 '1234:2,5678:3'
        :param area: 地区id
        :param stock_interval: 查询库存时间间隔，可选参数，默认3秒
        :param submit_retry: 提交订单失败后重试次数，可选参数，默认3次
        :param submit_interval: 提交订单失败后重试时间间隔，可选参数，默认5秒
        :return:
        """
        #先获取好购物车信息，以便知道有库存后不用重新爬取购物车信息而影响效率，代码来自get_cart_detail()
        url = 'https://cart.jd.com/cart.action'
        resp = self.sess.get(url)
        soup = BeautifulSoup(resp.text, "html.parser")
        
        cart_detail = dict()
        for item in soup.find_all(class_='item-item'):
            try:
                sku_id = item['skuid']  # 商品id
                # 例如：['increment', '8888', '100001071956', '1', '13', '0', '50067652554']
                # ['increment', '8888', '100002404322', '2', '1', '0']
                item_attr_list = item.find(class_='increment')['id'].split('_')
                p_type = item_attr_list[4]
                promo_id = target_id = item_attr_list[-1] if len(item_attr_list) == 7 else 0

                cart_detail[sku_id] = {
                    'name': get_tag_value(item.select('div.p-name a')),  # 商品名称
                    'verder_id': item['venderid'],  # 商家id
                    'count': int(item['num']),  # 数量
                    'unit_price': get_tag_value(item.select('div.p-price strong'))[1:],  # 单价
                    'total_price': get_tag_value(item.select('div.p-sum strong'))[1:],  # 总价
                    'is_selected': 'item-selected' in item['class'],  # 商品是否被勾选
                    'p_type': p_type,
                    'target_id': target_id,
                    'promo_id': promo_id
                }
            except Exception as e:
                logger.error("某商品在购物车中的信息无法解析，报错信息: %s，该商品自动忽略。 %s", e, item)
        cart=self.get_cart_detail()
        cart_item = cart.get(sku_id)#后面修改商品数量要用
        print("报告！购物车读取完毕！")
        #logger.info('购物车信息：%s', cart_item)        
        
        #遍历查询sku_ids是否有货并最终下单，代码来自buy_item_in_stock
        items_dict = parse_sku_id(sku_ids)
        #items_list = list(items_dict.keys())
        area_id = parse_area_id(area=area)
        while True:
            for (sku_id, count) in items_dict.items():
                if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area_id):  
                    logger.info('%s 不满足下单条件，%ss后进行下一次查询', sku_id, stock_interval)
                else:
                    logger.info('%s 满足下单条件，开始执行', sku_id)
                
                    #判断是否已在购物车
                    if sku_id in cart:
                
                        #修改购物车数量，以达到勾选商品的目的，代码来自_add_or_change_cart_item
                        url = "https://cart.jd.com/changeNum.action"
                        data = {
                                't': 0,
                                'venderId': cart_item.get('vender_id'),
                                'pid': sku_id,
                                'pcount': 1,
                                'ptype': cart_item.get('p_type'),
                                'targetId': cart_item.get('target_id'),
                                'promoID': cart_item.get('promo_id'),
                                'outSkus': '',
                                'random': random.random(),
                                # 'locationId'
                                }
                        headers = {
                                'User-Agent': self.user_agent,
                                'Referer': 'https://cart.jd.com/cart',
                                }
                        resp = self.sess.post(url, data=data, headers=headers)
            
                        if self.submit_order_with_retry(submit_retry, submit_interval):
                            return
                        else:
                            print("商品不在购物车中")
                            self._cancel_select_all_cart_item()
                            self._add_or_change_cart_item(self.get_cart_detail(), sku_id, count)
                            if self.submit_order_with_retry(submit_retry, submit_interval):
                                return

**Comment by 1286320807** [comment]
请问你直接下单，有成功买到过口罩吗。

**Comment by zaiweijian** [comment]
> 请问你直接下单，有成功买到过口罩吗。

没有，咱们就是抢个乐。

**Comment by mruray** [comment]
> > 找了另一个项目的查询库存订单，一直显示没货。。。这一个时时不时显示有货，但是下单失败。
> > 2020-02-09 09：26：16,982 INFO：100002690366不满足下单条件，0.01s后进行下一次查询
> > 2020-02-09 09：26：17,062 INFO：100002690366不满足下单条件，0.01s后进行下一次查询一次查询
> > 2020-02-09 09：26：17,191信息：100002690366满足下单条件，开始执行
> > 2020-02-09 09：26：17,312信息：订单提交失败，错误代码：600158，返回信息：3M口罩KN95耳戴折叠式9501VT带阀颗粒物防护口罩独立包装25只/盒商品无货
> > 出现好一次这种情况，这种零点几秒就没货了。
> 
> 请问 如何跳过 购物车显示信息: 直接提交订单 , 就像你这样满足条件 直接下单

根据作者的代码修改了一份，初步测试可以。现在我是通过修改数量来达到购物车勾选的，不知道有有没有更有效的方法。代码刚才发了好像格式不对齐，我新评论一下。

**Comment by mruray** [comment]
def buy_item_in_cart(self,sku_ids,area,stock_interval=3, submit_retry=3, submit_interval=0.001):
        """为提高效率，心仪商品全部提前加入购物车，检测库存有货立马购物车中开始提交
        :param sku_ids: 商品id。可以设置多个商品，也可以带数量，如：'1234' 或 '1234,5678' 或 '1234:2' 或 '1234:2,5678:3'
        :param area: 地区id
        :param stock_interval: 查询库存时间间隔，可选参数，默认3秒
        :param submit_retry: 提交订单失败后重试次数，可选参数，默认3次
        :param submit_interval: 提交订单失败后重试时间间隔，可选参数，默认5秒
        :return:
        """
        #先获取好购物车信息，以便知道有库存后不用重新爬取购物车信息而影响效率，代码来自get_cart_detail()
        url = 'https://cart.jd.com/cart.action'
        resp = self.sess.get(url)
        soup = BeautifulSoup(resp.text, "html.parser")
        
        cart_detail = dict()
        for item in soup.find_all(class_='item-item'):
            try:
                sku_id = item['skuid']  # 商品id
                # 例如：['increment', '8888', '100001071956', '1', '13', '0', '50067652554']
                # ['increment', '8888', '100002404322', '2', '1', '0']
                item_attr_list = item.find(class_='increment')['id'].split('_')
                p_type = item_attr_list[4]
                promo_id = target_id = item_attr_list[-1] if len(item_attr_list) == 7 else 0

                cart_detail[sku_id] = {
                    'name': get_tag_value(item.select('div.p-name a')),  # 商品名称
                    'verder_id': item['venderid'],  # 商家id
                    'count': int(item['num']),  # 数量
                    'unit_price': get_tag_value(item.select('div.p-price strong'))[1:],  # 单价
                    'total_price': get_tag_value(item.select('div.p-sum strong'))[1:],  # 总价
                    'is_selected': 'item-selected' in item['class'],  # 商品是否被勾选
                    'p_type': p_type,
                    'target_id': target_id,
                    'promo_id': promo_id
                }
            except Exception as e:
                logger.error("某商品在购物车中的信息无法解析，报错信息: %s，该商品自动忽略。 %s", e, item)
        cart=self.get_cart_detail()#后面修改商品数量要用 
        print("报告！购物车读取完毕！")
        #logger.info('购物车信息：%s', cart_item)        
        
        #遍历查询sku_ids是否有货并最终下单，代码来自buy_item_in_stock
        items_dict = parse_sku_id(sku_ids)
        #items_list = list(items_dict.keys())
        area_id = parse_area_id(area=area)
        while True:
            for (sku_id, count) in items_dict.items():
                cart_item = cart.get(sku_id)
                if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area_id):  
                    logger.info('%s 不满足下单条件，%ss后进行下一次查询', sku_id, stock_interval)
                else:
                    logger.info('%s 满足下单条件，开始执行', sku_id)
                
                    #判断是否已在购物车
                    if sku_id in cart:
                        print("商品在购物车中")
                        
                        #修改购物车数量，以达到勾选商品的目的，代码来自_add_or_change_cart_item
                        url = "https://cart.jd.com/changeNum.action"
                        data = {
                                't': 0,
                                'venderId': cart_item.get('vender_id'),
                                'pid': sku_id,
                                'pcount': 1,
                                'ptype': cart_item.get('p_type'),
                                'targetId': cart_item.get('target_id'),
                                'promoID': cart_item.get('promo_id'),
                                'outSkus': '',
                                'random': random.random(),
                                # 'locationId'
                                }
                        headers = {
                                'User-Agent': self.user_agent,
                                'Referer': 'https://cart.jd.com/cart',
                                }
                        resp = self.sess.post(url, data=data, headers=headers)
            
                        if self.submit_order_with_retry(submit_retry, submit_interval):
                            return
                        else:
                            print("商品不在购物车中")
                            self._cancel_select_all_cart_item()
                            self._add_or_change_cart_item(self.get_cart_detail(), sku_id, count)
                            if self.submit_order_with_retry(submit_retry, submit_interval):
                                return

**Comment by Hywans** [comment]
> def buy_item_in_cart(self,sku_ids,area,stock_interval=3, submit_retry=3, submit_interval=0.001):
> """为提高效率，心仪商品全部提前加入购物车，检测库存有货立马购物车中开始提交
> :param sku_ids: 商品id。可以设置多个商品，也可以带数量，如：'1234' 或 '1234,5678' 或 '1234:2' 或 '1234:2,5678:3'
> :param area: 地区id
> :param stock_interval: 查询库存时间间隔，可选参数，默认3秒
> :param submit_retry: 提交订单失败后重试次数，可选参数，默认3次
> :param submit_interval: 提交订单失败后重试时间间隔，可选参数，默认5秒
> :return:
> """
> #先获取好购物车信息，以便知道有库存后不用重新爬取购物车信息而影响效率，代码来自get_cart_detail()
> url = 'https://cart.jd.com/cart.action'
> resp = self.sess.get(url)
> soup = BeautifulSoup(resp.text, "html.parser")
> 
> ```
>     cart_detail = dict()
>     for item in soup.find_all(class_='item-item'):
>         try:
>             sku_id = item['skuid']  # 商品id
>             # 例如：['increment', '8888', '100001071956', '1', '13', '0', '50067652554']
>             # ['increment', '8888', '100002404322', '2', '1', '0']
>             item_attr_list = item.find(class_='increment')['id'].split('_')
>             p_type = item_attr_list[4]
>             promo_id = target_id = item_attr_list[-1] if len(item_attr_list) == 7 else 0
> 
>             cart_detail[sku_id] = {
>                 'name': get_tag_value(item.select('div.p-name a')),  # 商品名称
>                 'verder_id': item['venderid'],  # 商家id
>                 'count': int(item['num']),  # 数量
>                 'unit_price': get_tag_value(item.select('div.p-price strong'))[1:],  # 单价
>                 'total_price': get_tag_value(item.select('div.p-sum strong'))[1:],  # 总价
>                 'is_selected': 'item-selected' in item['class'],  # 商品是否被勾选
>                 'p_type': p_type,
>                 'target_id': target_id,
>                 'promo_id': promo_id
>             }
>         except Exception as e:
>             logger.error("某商品在购物车中的信息无法解析，报错信息: %s，该商品自动忽略。 %s", e, item)
>     cart=self.get_cart_detail()#后面修改商品数量要用 
>     print("报告！购物车读取完毕！")
>     #logger.info('购物车信息：%s', cart_item)        
>     
>     #遍历查询sku_ids是否有货并最终下单，代码来自buy_item_in_stock
>     items_dict = parse_sku_id(sku_ids)
>     #items_list = list(items_dict.keys())
>     area_id = parse_area_id(area=area)
>     while True:
>         for (sku_id, count) in items_dict.items():
>             cart_item = cart.get(sku_id)
>             if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area_id):  
>                 logger.info('%s 不满足下单条件，%ss后进行下一次查询', sku_id, stock_interval)
>             else:
>                 logger.info('%s 满足下单条件，开始执行', sku_id)
>             
>                 #判断是否已在购物车
>                 if sku_id in cart:
>                     print("商品在购物车中")
>                     
>                     #修改购物车数量，以达到勾选商品的目的，代码来自_add_or_change_cart_item
>                     url = "https://cart.jd.com/changeNum.action"
>                     data = {
>                             't': 0,
>                             'venderId': cart_item.get('vender_id'),
>                             'pid': sku_id,
>                             'pcount': 1,
>                             'ptype': cart_item.get('p_type'),
>                             'targetId': cart_item.get('target_id'),
>                             'promoID': cart_item.get('promo_id'),
>                             'outSkus': '',
>                             'random': random.random(),
>                             # 'locationId'
>                             }
>                     headers = {
>                             'User-Agent': self.user_agent,
>                             'Referer': 'https://cart.jd.com/cart',
>                             }
>                     resp = self.sess.post(url, data=data, headers=headers)
>         
>                     if self.submit_order_with_retry(submit_retry, submit_interval):
>                         return
>                     else:
>                         print("商品不在购物车中")
>                         self._cancel_select_all_cart_item()
>                         self._add_or_change_cart_item(self.get_cart_detail(), sku_id, count)
>                         if self.submit_order_with_retry(submit_retry, submit_interval):
>                             return
> ```
我想知道你优化的这个 抢到了吗

**Comment by mruray** [comment]
> > def buy_item_in_cart(self,sku_ids,area,stock_interval=3, submit_retry=3, submit_interval=0.001):
> > """为提高效率，心仪商品全部提前加入购物车，检测库存有货立马购物车中开始提交
> > :param sku_ids: 商品id。可以设置多个商品，也可以带数量，如：'1234' 或 '1234,5678' 或 '1234:2' 或 '1234:2,5678:3'
> > :param area: 地区id
> > :param stock_interval: 查询库存时间间隔，可选参数，默认3秒
> > :param submit_retry: 提交订单失败后重试次数，可选参数，默认3次
> > :param submit_interval: 提交订单失败后重试时间间隔，可选参数，默认5秒
> > :return:
> > """
> > #先获取好购物车信息，以便知道有库存后不用重新爬取购物车信息而影响效率，代码来自get_cart_detail()
> > url = 'https://cart.jd.com/cart.action'
> > resp = self.sess.get(url)
> > soup = BeautifulSoup(resp.text, "html.parser")
> > ```
> >     cart_detail = dict()
> >     for item in soup.find_all(class_='item-item'):
> >         try:
> >             sku_id = item['skuid']  # 商品id
> >             # 例如：['increment', '8888', '100001071956', '1', '13', '0', '50067652554']
> >             # ['increment', '8888', '100002404322', '2', '1', '0']
> >             item_attr_list = item.find(class_='increment')['id'].split('_')
> >             p_type = item_attr_list[4]
> >             promo_id = target_id = item_attr_list[-1] if len(item_attr_list) == 7 else 0
> > 
> >             cart_detail[sku_id] = {
> >                 'name': get_tag_value(item.select('div.p-name a')),  # 商品名称
> >                 'verder_id': item['venderid'],  # 商家id
> >                 'count': int(item['num']),  # 数量
> >                 'unit_price': get_tag_value(item.select('div.p-price strong'))[1:],  # 单价
> >                 'total_price': get_tag_value(item.select('div.p-sum strong'))[1:],  # 总价
> >                 'is_selected': 'item-selected' in item['class'],  # 商品是否被勾选
> >                 'p_type': p_type,
> >                 'target_id': target_id,
> >                 'promo_id': promo_id
> >             }
> >         except Exception as e:
> >             logger.error("某商品在购物车中的信息无法解析，报错信息: %s，该商品自动忽略。 %s", e, item)
> >     cart=self.get_cart_detail()#后面修改商品数量要用 
> >     print("报告！购物车读取完毕！")
> >     #logger.info('购物车信息：%s', cart_item)        
> >     
> >     #遍历查询sku_ids是否有货并最终下单，代码来自buy_item_in_stock
> >     items_dict = parse_sku_id(sku_ids)
> >     #items_list = list(items_dict.keys())
> >     area_id = parse_area_id(area=area)
> >     while True:
> >         for (sku_id, count) in items_dict.items():
> >             cart_item = cart.get(sku_id)
> >             if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area_id):  
> >                 logger.info('%s 不满足下单条件，%ss后进行下一次查询', sku_id, stock_interval)
> >             else:
> >                 logger.info('%s 满足下单条件，开始执行', sku_id)
> >             
> >                 #判断是否已在购物车
> >                 if sku_id in cart:
> >                     print("商品在购物车中")
> >                     
> >                     #修改购物车数量，以达到勾选商品的目的，代码来自_add_or_change_cart_item
> >                     url = "https://cart.jd.com/changeNum.action"
> >                     data = {
> >                             't': 0,
> >                             'venderId': cart_item.get('vender_id'),
> >                             'pid': sku_id,
> >                             'pcount': 1,
> >                             'ptype': cart_item.get('p_type'),
> >                             'targetId': cart_item.get('target_id'),
> >                             'promoID': cart_item.get('promo_id'),
> >                             'outSkus': '',
> >                             'random': random.random(),
> >                             # 'locationId'
> >                             }
> >                     headers = {
> >                             'User-Agent': self.user_agent,
> >                             'Referer': 'https://cart.jd.com/cart',
> >                             }
> >                     resp = self.sess.post(url, data=data, headers=headers)
> >         
> >                     if self.submit_order_with_retry(submit_retry, submit_interval):
> >                         return
> >                     else:
> >                         print("商品不在购物车中")
> >                         self._cancel_select_all_cart_item()
> >                         self._add_or_change_cart_item(self.get_cart_detail(), sku_id, count)
> >                         if self.submit_order_with_retry(submit_retry, submit_interval):
> >                             return
> > ```
> 
> 我想知道你优化的这个 抢到了吗

有抢到星工的，可能发货量大吧

**Comment by 1286320807** [comment]
def buy_item_in_cart(self,sku_ids,area,stock_interval=3, submit_retry=3, submit_interval=0.001):
"""为提高效率，心仪商品全部提前加入购物车，检测库存有货立马购物车中开始提交
:param sku_ids: 商品id。可以设置多个商品，也可以带数量，如：'1234' 或 '1234,5678' 或 '1234:2' 或 '1234:2,5678:3'
:param area: 地区id
:param stock_interval: 查询库存时间间隔，可选参数，默认3秒
:param submit_retry: 提交订单失败后重试次数，可选参数，默认3次
:param submit_interval: 提交订单失败后重试时间间隔，可选参数，默认5秒
:return:
"""

**下面部分要不要缩进去？**

#先获取好购物车信息，以便知道有库存后不用重新爬取购物车信息而影响效率，代码来自get_cart_detail()
url = 'https://cart.jd.com/cart.action'
resp = self.sess.get(url)
soup = BeautifulSoup(resp.text, "html.parser")

**Comment by mruray** [comment]
`    def buy_item_in_cart(self,sku_ids,area,stock_interval=3, submit_retry=3, submit_interval=0.001):
        """为提高效率，心仪商品全部提前加入购物车，检测库存有货立马购物车中开始提交
        :param sku_ids: 商品id。可以设置多个商品，也可以带数量，如：'1234' 或 '1234,5678' 或 '1234:2' 或 '1234:2,5678:3'
        :param area: 地区id
        :param stock_interval: 查询库存时间间隔，可选参数，默认3秒
        :param submit_retry: 提交订单失败后重试次数，可选参数，默认3次
        :param submit_interval: 提交订单失败后重试时间间隔，可选参数，默认5秒
        :return:
        """
        #先获取好购物车信息，以便知道有库存后不用重新爬取购物车信息而影响效率，代码来自get_cart_detail()
        url = 'https://cart.jd.com/cart.action'
        resp = self.sess.get(url)
        soup = BeautifulSoup(resp.text, "html.parser")
        
        cart_detail = dict()
        for item in soup.find_all(class_='item-item'):
            try:
                sku_id = item['skuid']  # 商品id
                # 例如：['increment', '8888', '100001071956', '1', '13', '0', '50067652554']
                # ['increment', '8888', '100002404322', '2', '1', '0']
                item_attr_list = item.find(class_='increment')['id'].split('_')
                p_type = item_attr_list[4]
                promo_id = target_id = item_attr_list[-1] if len(item_attr_list) == 7 else 0

                cart_detail[sku_id] = {
                    'name': get_tag_value(item.select('div.p-name a')),  # 商品名称
                    'verder_id': item['venderid'],  # 商家id
                    'count': int(item['num']),  # 数量
                    'unit_price': get_tag_value(item.select('div.p-price strong'))[1:],  # 单价
                    'total_price': get_tag_value(item.select('div.p-sum strong'))[1:],  # 总价
                    'is_selected': 'item-selected' in item['class'],  # 商品是否被勾选
                    'p_type': p_type,
                    'target_id': target_id,
                    'promo_id': promo_id
                }
            except Exception as e:
                logger.error("某商品在购物车中的信息无法解析，报错信息: %s，该商品自动忽略。 %s", e, item)
        cart=self.get_cart_detail()#后面修改商品数量要用 
        print("报告！购物车读取完毕！")
        #logger.info('购物车信息：%s', cart_item)        
        
        #遍历查询sku_ids是否有货并最终下单，代码来自buy_item_in_stock
        items_dict = parse_sku_id(sku_ids)
        #items_list = list(items_dict.keys())
        area_id = parse_area_id(area=area)
        while True:
            for (sku_id, count) in items_dict.items():
                cart_item = cart.get(sku_id)
                if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area_id):  
                    logger.info('%s 不满足下单条件，%ss后进行下一次查询', sku_id, stock_interval)
                else:
                    logger.info('%s 满足下单条件，开始执行', sku_id)
                
                    #判断是否已在购物车
                    if sku_id in cart:
                        print("商品在购物车中")
                        
                        #修改购物车数量，以达到勾选商品的目的，代码来自_add_or_change_cart_item
                        url = "https://cart.jd.com/changeNum.action"
                        data = {
                                't': 0,
                                'venderId': cart_item.get('vender_id'),
                                'pid': sku_id,
                                'pcount': 1,
                                'ptype': cart_item.get('p_type'),
                                'targetId': cart_item.get('target_id'),
                                'promoID': cart_item.get('promo_id'),
                                'outSkus': '',
                                'random': random.random(),
                                # 'locationId'
                                }
                        headers = {
                                'User-Agent': self.user_agent,
                                'Referer': 'https://cart.jd.com/cart',
                                }
                        resp = self.sess.post(url, data=data, headers=headers)
            
                        if self.submit_order_with_retry(submit_retry, submit_interval):
                            return
                        else:
                            print("商品不在购物车中")
                            self._cancel_select_all_cart_item()
                            self._add_or_change_cart_item(self.get_cart_detail(), sku_id, count)
                            if self.submit_order_with_retry(submit_retry, submit_interval):
                                return`

**Comment by mruray** [comment]
> def buy_item_in_cart(self,sku_ids,area,stock_interval=3, submit_retry=3, submit_interval=0.001):
> """为提高效率，心仪商品全部提前加入购物车，检测库存有货立马购物车中开始提交
> :param sku_ids: 商品id。可以设置多个商品，也可以带数量，如：'1234' 或 '1234,5678' 或 '1234:2' 或 '1234:2,5678:3'
> :param area: 地区id
> :param stock_interval: 查询库存时间间隔，可选参数，默认3秒
> :param submit_retry: 提交订单失败后重试次数，可选参数，默认3次
> :param submit_interval: 提交订单失败后重试时间间隔，可选参数，默认5秒
> :return:
> """
> 
> **下面部分要不要缩进去？**
> 
> #先获取好购物车信息，以便知道有库存后不用重新爬取购物车信息而影响效率，代码来自get_cart_detail()
> url = 'https://cart.jd.com/cart.action'
> resp = self.sess.get(url)
> soup = BeautifulSoup(resp.text, "html.parser")
不用，跟"""对齐的

**Comment by jy024929** [comment]
> def buy_item_in_cart(self,sku_ids,area,stock_interval=3, submit_retry=3, submit_interval=0.001):
> """为提高效率，心仪商品全部提前加入购物车，检测库存有货立马购物车中开始提交
> :param sku_ids: 商品id。可以设置多个商品，也可以带数量，如：'1234' 或 '1234,5678' 或 '1234:2' 或 '1234:2,5678:3'
> :param area: 地区id
> :param stock_interval: 查询库存时间间隔，可选参数，默认3秒
> :param submit_retry: 提交订单失败后重试次数，可选参数，默认3次
> :param submit_interval: 提交订单失败后重试时间间隔，可选参数，默认5秒
> :return:
> """
> #先获取好购物车信息，以便知道有库存后不用重新爬取购物车信息而影响效率，代码来自get_cart_detail()
> url = 'https://cart.jd.com/cart.action'
> resp = self.sess.get(url)
> soup = BeautifulSoup(resp.text, "html.parser")
> 
> ```
>     cart_detail = dict()
>     for item in soup.find_all(class_='item-item'):
>         try:
>             sku_id = item['skuid']  # 商品id
>             # 例如：['increment', '8888', '100001071956', '1', '13', '0', '50067652554']
>             # ['increment', '8888', '100002404322', '2', '1', '0']
>             item_attr_list = item.find(class_='increment')['id'].split('_')
>             p_type = item_attr_list[4]
>             promo_id = target_id = item_attr_list[-1] if len(item_attr_list) == 7 else 0
> 
>             cart_detail[sku_id] = {
>                 'name': get_tag_value(item.select('div.p-name a')),  # 商品名称
>                 'verder_id': item['venderid'],  # 商家id
>                 'count': int(item['num']),  # 数量
>                 'unit_price': get_tag_value(item.select('div.p-price strong'))[1:],  # 单价
>                 'total_price': get_tag_value(item.select('div.p-sum strong'))[1:],  # 总价
>                 'is_selected': 'item-selected' in item['class'],  # 商品是否被勾选
>                 'p_type': p_type,
>                 'target_id': target_id,
>                 'promo_id': promo_id
>             }
>         except Exception as e:
>             logger.error("某商品在购物车中的信息无法解析，报错信息: %s，该商品自动忽略。 %s", e, item)
>     cart=self.get_cart_detail()#后面修改商品数量要用 
>     print("报告！购物车读取完毕！")
>     #logger.info('购物车信息：%s', cart_item)        
>     
>     #遍历查询sku_ids是否有货并最终下单，代码来自buy_item_in_stock
>     items_dict = parse_sku_id(sku_ids)
>     #items_list = list(items_dict.keys())
>     area_id = parse_area_id(area=area)
>     while True:
>         for (sku_id, count) in items_dict.items():
>             cart_item = cart.get(sku_id)
>             if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area_id):  
>                 logger.info('%s 不满足下单条件，%ss后进行下一次查询', sku_id, stock_interval)
>             else:
>                 logger.info('%s 满足下单条件，开始执行', sku_id)
>             
>                 #判断是否已在购物车
>                 if sku_id in cart:
>                     print("商品在购物车中")
>                     
>                     #修改购物车数量，以达到勾选商品的目的，代码来自_add_or_change_cart_item
>                     url = "https://cart.jd.com/changeNum.action"
>                     data = {
>                             't': 0,
>                             'venderId': cart_item.get('vender_id'),
>                             'pid': sku_id,
>                             'pcount': 1,
>                             'ptype': cart_item.get('p_type'),
>                             'targetId': cart_item.get('target_id'),
>                             'promoID': cart_item.get('promo_id'),
>                             'outSkus': '',
>                             'random': random.random(),
>                             # 'locationId'
>                             }
>                     headers = {
>                             'User-Agent': self.user_agent,
>                             'Referer': 'https://cart.jd.com/cart',
>                             }
>                     resp = self.sess.post(url, data=data, headers=headers)
>         
>                     if self.submit_order_with_retry(submit_retry, submit_interval):
>                         return
>                     else:
>                         print("商品不在购物车中")
>                         self._cancel_select_all_cart_item()
>                         self._add_or_change_cart_item(self.get_cart_detail(), sku_id, count)
>                         if self.submit_order_with_retry(submit_retry, submit_interval):
>                             return
> ```
为什么我根据你的改好后，显示是这样的和楼主显示的不一样？
2020-02-18 16:00:03,165 INFO: 1683285455 满足下单条件，开始执行
商品在购物车中
2020-02-18 16:00:03,354 INFO: 第[1/3]次尝试提交订单
2020-02-18 16:00:04,104 INFO: 下单信息：{'address': '', 'receiver': ' ', 'total_price': '10.38', 'items': []}
2020-02-18 16:00:04,239 INFO: 订单提交失败, 错误码：600158, 返回信息：全棉时代 一次性口罩 优质棉无纺布三层防护 2片/袋商 品无货
