### ISSUE TITLE
submit_order_by_stock问题

### ISSUE THREAD

**Issue by supersf** [tychxn/jd-assistant#9]
def submit_order_by_stock(self, sku_id='251837', area='12_904_3375', interval=3):
        while True:
            if self.if_item_in_stock(sku_id=sku_id, area=area):
                print(get_current_time(), '%s有货了，正在提交订单……' % sku_id)
                self.add_item_to_cart(sku_id)  ##少了这个好像不能提交订单呀
                self.submit_order()
                break
            else:
                print(get_current_time(), '%s无货，准备下一次查询……' % sku_id)
                time.sleep(interval)

**Comment by tychxn** [comment]
的确，缺少了`self.add_item_to_cart(sku_id)`无法提交订单。
但是将这个加在此处会影响提交订单效率，建议先添加到购物车，后执行有库存提交操作：
```python
asst.clear_cart()  # 清空购物车
asst.add_item_to_cart(sku_id='xxx')  # 添加商品
asst.submit_order_by_stock(sku_id='xxx', area='xxx')  # 有货就提交订单
```
