### ISSUE TITLE
验证码问题：大佬帮测一下 货号：65466451629

### ISSUE THREAD

**Issue by For515** [tychxn/jd-assistant#94]
验证码的问题，帮忙测一下65466451629，每天晚上11点上货可能前后差20秒，每天因为验证码卡住，您帮测一下看看今天你那边会不会也提示验证码，为此我和京东客服吼叫了半天。。。。我自己的是PLUS，9号11点换了个白皮号也提示验证码。我现在不敢肯定到底是风控还是这个商品就是加保护了

**Comment by hui-shao** [comment]
应该是加保护了，你可以看看我的这个，有人测过了
https://github.com/tychxn/jd-assistant/issues/85

**Comment by tychxn** [comment]
估计是ip被风控了 换账号也不行

**Comment by James-yang-china** [comment]
这几天的口罩，很正常
