### ISSUE TITLE
提交订单返回 "抱歉，您购买的商品不支持开电子发票"

### ISSUE THREAD

**Issue by noname2001** [tychxn/jd-assistant#96]
预约购买的商品，到时间后第一次提交订单返回
"抱歉，您购买的商品不支持开电子发票"

**Comment by tychxn** [comment]
应该是第三方商品，会自动切换为纸质发票进行尝试。

**Comment by ariwori** [comment]
可以指定吗，一旦重试就没货了

**Comment by kraml** [comment]
我也遇到这个几次了。但是我手工下单测试时每次默认的都是不开发票，不知道为什么脚本自动下单会选择开发票。
